Added optional argument to expose DB port
magento/magento-cloud-docker pull request #101
Opened 2019-11-11 14:53 UTC by drpayyne

### Description

-  Added optional argument `--expose-db-port=<PORT>` to `bin/ece-docker build:compose` to expose DB port to the host

### Fixed Issues

-  magento/magento-cloud-docker#80: Open up port 3306 for Database

### Manual testing scenarios
1. Run `bin/ece-docker build:compose --expose-db-port=4000` to expose port 4000 to host
2. Run `bin/ece-docker build:compose` without `--expose-db-port` argument to hide DB from host (existing funcitonality)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2019-11-11 14:56 UTC, drpayyne commented
Hi @shiftedreality, while setting up this repository in my local, I ran into lots of issues regarding missing `.yaml` files and incorrect paths to locate the mentioned missing `.yaml` files. Is this expected?

2019-11-11 17:06 UTC, mattskr submitted a review, later dismissed

2019-11-11 20:07 UTC, shiftedreality requested changes
Overall looks good, requested minor changes

2019-11-11 20:07 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +        if($exposedDbPort = $input->getOption(self::OPTION_EXPOSE_DB_PORT)) {
This can be safely added to map:

```
    private static $optionsMap = [
        self::OPTION_PHP => ServiceInterface::NAME_PHP,
        self::OPTION_DB => ServiceInterface::NAME_DB,
        self::OPTION_NGINX => ServiceInterface::NAME_NGINX,
        self::OPTION_REDIS => ServiceInterface::NAME_REDIS,
        self::OPTION_ES => ServiceInterface::NAME_ELASTICSEARCH,
        self::OPTION_NODE => ServiceInterface::NAME_NODE,
        self::OPTION_RABBIT_MQ => ServiceInterface::NAME_RABBITMQ,
        self::OPTION_SELENIUM_VERSION => ServiceFactory::SERVICE_SELENIUM_VERSION,
        self::OPTION_SELENIUM_IMAGE => ServiceFactory::SERVICE_SELENIUM_IMAGE
    ];
```

2019-11-11 20:07 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +        $dbPorts = $hostPort ? "$hostPort:3306" : "3306";
Please use single quotes in an `else` statement

2019-11-12 04:41 UTC, drpayyne commented on src/Command/BuildCompose.php
> +        if($exposedDbPort = $input->getOption(self::OPTION_EXPOSE_DB_PORT)) {
Any suggestions on where I can place the constant for the `--expose-db-port` argument? Not sure where to place it since it **isn't** a service like the others.

2019-11-12 04:42 UTC, drpayyne commented on src/Compose/ProductionBuilder.php
> +        $dbPorts = $hostPort ? "$hostPort:3306" : "3306";
Fixed it, thanks!

2019-11-12 14:29 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +        if($exposedDbPort = $input->getOption(self::OPTION_EXPOSE_DB_PORT)) {
Just put to `ProductionBuilder`, we already have there similar args

2019-11-12 14:48 UTC, drpayyne commented on src/Command/BuildCompose.php
> +        if($exposedDbPort = $input->getOption(self::OPTION_EXPOSE_DB_PORT)) {
@shiftedreality, I've fixed it. Thank you!

2019-11-12 14:52 UTC, drpayyne commented on src/Command/BuildCompose.php
> +        self::OPTION_EXPOSE_DB_PORT => self::OPTION_EXPOSE_DB_PORT
I reused the key, since ProductionBuilder already has the same key, and unlike the other services, this argument will have same name and value. @shiftedreality

2019-11-12 14:58 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +        self::OPTION_EXPOSE_DB_PORT => self::OPTION_EXPOSE_DB_PORT
YOu cannot be sure those 2 constants will remain the same, please use the constant from `ProductionBuilder`

2019-11-12 15:00 UTC, drpayyne commented on src/Command/BuildCompose.php
> +        self::OPTION_EXPOSE_DB_PORT => self::OPTION_EXPOSE_DB_PORT
Fixed it, @shiftedreality. Apologies for the confusion!

2019-11-12 15:00 UTC, shiftedreality commented
This is simple script to test Docker integration:

```
#!/usr/bin/env php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
require __DIR__ . '/../bootstrap.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\Config\FileLocator;
use Magento\CloudDocker\Filesystem\DirectoryList;

$container = new ContainerBuilder();
$container->set(DirectoryList::class, new DirectoryList(
    dirname(__DIR__),
    __DIR__ . '/../../YOUR_PROJECT',
    __DIR__ . '/../../YOUR_PROJECT'
));

$loader = new XmlFileLoader($container, new FileLocator(__DIR__ . '/../config'));
$loader->load('services.xml');

$container->compile();

$application = new Magento\CloudDocker\Application($container);
$application->run();

```

Place it as `./bin/dev-ece-docker`:

```
-- YOUR_PROJECT
-- magento-cloud-docker/bin/dev-ece-docker
```

2019-11-12 15:01 UTC, shiftedreality approved these changes

2019-11-12 15:01 UTC, shiftedreality commented
@mattskr please approve 1 more time

2019-11-12 17:00 UTC, mattskr approved these changes

2019-11-12 19:27 UTC, andriyShevtsov commented
QA approved

2019-11-12 20:15 UTC, merged