Added pass for xdebug requests
magento/magento-cloud-docker pull request #111
Opened 2019-12-12 15:57 UTC by aepod

Dimitar Ivanov provided the code for this in the community engineering slack.

### Description
This fixes the varnish+xdebug issue.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento-cloud-docker/issues/110

### Manual testing scenarios
1. Enable varnish and xdebug, and do a step debug.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages

2019-12-12 16:21 UTC, shiftedreality commented
Thank you for your contribution!

Changing target to 1.0 to include into the upcoming release.

2019-12-12 16:23 UTC, shiftedreality commented
Created task https://magento2.atlassian.net/browse/MAGECLOUD-4873

2019-12-13 04:03 UTC, joeshelton-wagento commented
Possible to only check for the existence of the cookie, as opposed to the value "PHPSTORM"? This would make it more versatile and agnostic.

Also, some people use a GET or POST parameter "XDEBUG_SESSION_START". https://xdebug.org/docs/remote

2019-12-13 12:27 UTC, aepod commented
https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-development-debug.html
This only provides instructions for PHPStorm, I think for now this PR is fine, it matches with given instructions. We can improve on this later, and add support for other IDE, but as far as I can see this matches with documentation and should be good to go for now.

Please let me know if it needs to be adjusted.

2019-12-17 14:30 UTC, shiftedreality approved these changes

2019-12-17 14:38 UTC, oshmyheliuk submitted a review, later dismissed

2019-12-17 16:05 UTC, shiftedreality commented
@aepod could you please add the same change to Varnish 4.0 image?

2019-12-17 16:13 UTC, shiftedreality requested changes

2019-12-17 16:13 UTC, shiftedreality commented on images/varnish/6.2/etc/default.vcl
> +    if (req.http.Cookie ~ "(^|;\s*)(XDEBUG_SESSION=PHPSTORM)(;|$)") {
Please add Varnish 4.0 support here

2019-12-18 17:04 UTC, shiftedreality commented
Grooming comment: Make session variable broader to include more variety of IDEs

2019-12-23 19:20 UTC, aepod commented
PR has been updated, it now just checks for the cookie (not contents) also it is added to both v4 and v6 varnish config.

2020-01-02 16:18 UTC, shiftedreality approved these changes

2020-01-02 16:25 UTC, oshmyheliuk approved these changes

2020-01-02 21:38 UTC, mveeramneni commented
QA Approved

2020-01-02 21:53 UTC, merged

2020-01-02 21:54 UTC, shiftedreality commented
@aepod will you add doc update mentioning this change or should I create a task internally?