MAGECLOUD-4486: Docker functional tests and CI with ece-tools test framework
magento/magento-cloud-docker pull request #120
Opened 2020-01-09 16:54 UTC by BaDos

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-02-14 20:36 UTC, bbatsche requested changes

2020-02-14 20:36 UTC, bbatsche commented on .travis.yml
> +  - echo "COMPOSER_GITHUB_TOKEN=${GITHUB_TOKEN}" >> ./.env
Why are we injecting environment variables into `.env`? The whole point of using `.env` is to simplify creating & managing environment variables, but in this context it would be simpler to either
1) Just update the environment variable names in Travis CI to the `COMPOSER_MAGENTO_USERNAME`, etc
or
2) Update the code to use the environment variables we're defining in Travis CI (`REPO_USERNAME`, etc)

2020-02-14 20:36 UTC, bbatsche commented on composer.json
> +        "symfony/dotenv": "^3.3||^4.0"
Are we using `.env` anywhere outside of Travis CI testing? Hopefully we can eliminate it entirely, but if not I think this should go in `require-dev`

2020-02-14 20:36 UTC, bbatsche commented on composer.json
> +        "symfony/dotenv": "^3.3||^4.0"
Codeception also support reading `.env` files natively, so I'm not sure what we would need Symfony's library anyway?

2020-02-14 20:36 UTC, bbatsche commented on tests/functional/Codeception/TestInfrastructure.php
> +            ->printOutput($this->_getConfig('printOutput'))
Duplicate method call

2020-02-14 20:36 UTC, bbatsche commented on tests/functional/Codeception/TestInfrastructure.php
> +     * Starts docke-sync
```suggestion
     * Starts docker-sync
```

2020-02-14 20:36 UTC, bbatsche commented on tests/functional/Codeception/TestInfrastructure.php
> +                    'password' => getenv('COMPOSER_MAGENTO_PASSWORD'),
Rather than reading environment variables directly in the module, Codeception should load the environment variables itself, and these configuration values should be set in `codeception.dist.yaml` https://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Parameters

2020-02-14 20:36 UTC, bbatsche commented on tests/functional/Robo/Tasks/CopyToDocker.php
> +        $command = 'docker cp [source] "$(docker-compose ps -q [container])":[destination]';
Why `strstr()` and not `sprintf()`? Either's fine, just odd that it's not consistent with other tasks.

2020-02-14 20:36 UTC, bbatsche commented on tests/functional/Robo/Tasks/EnvDown.php
> +    public function keepVolumes(bool $value): self
Might as well pass default of `true` here, just to make the API a little more friendly

2020-02-14 20:36 UTC, bbatsche commented on tests/travis/functional.sh
> +        echo "Need to fix composer's stuck"
Should this be taken care of before merging this PR, or is this something for the backlog?

2020-02-14 20:36 UTC, bbatsche commented on .travis.yml
> +  - if [ $TEST_SUITE == "static-unit" ]; then ./tests/travis/static-unit.sh; fi
I think this is a little friendlier for devs if we set it up as Composer scripts (like https://github.com/magento/ece-tools/blob/develop/composer.json#L71), but a shell script is fine

2020-02-18 15:30 UTC, BaDos commented on .travis.yml
> +  - echo "COMPOSER_GITHUB_TOKEN=${GITHUB_TOKEN}" >> ./.env
Users can run test on their local machines.
Using the file for these configurations is more convenient than creating environment variables.

2020-02-18 15:35 UTC, BaDos commented on composer.json
> +        "symfony/dotenv": "^3.3||^4.0"
**magento-cloud-docker** is like a framework for testing **ece-tools**, **magento-cloud-patches** and **magento-cloud-components**, so we should guarantee that all needed component will be downloaded by the composer. If we move this dependency to require-dev then the test framework does not work.

Regarding codeception - good point. I will use codeception reader for .env file.

2020-02-18 15:41 UTC, bbatsche commented on .travis.yml
> +  - echo "COMPOSER_GITHUB_TOKEN=${GITHUB_TOKEN}" >> ./.env
Using `.env` on a local machine makes sense, and users are capable of creating their own `.env` and `codeception.yaml` files to load it if they choose.

This is about environment variables in Travis though. And in Travis CI populating a `.env` file with variables that already come from the environment seems silly

2020-02-26 16:30 UTC, BaDos commented on tests/functional/Codeception/TestInfrastructure.php
> +            ->printOutput($this->_getConfig('printOutput'))
Fixed

2020-02-26 16:31 UTC, BaDos commented on tests/functional/Codeception/TestInfrastructure.php
> +     * Starts docke-sync
Fixed

2020-02-26 16:33 UTC, BaDos commented on tests/functional/Robo/Tasks/CopyToDocker.php
> +        $command = 'docker cp [source] "$(docker-compose ps -q [container])":[destination]';
Fixed

2020-02-26 16:34 UTC, BaDos commented on tests/functional/Robo/Tasks/EnvDown.php
> +    public function keepVolumes(bool $value): self
Agree, fixed

2020-02-26 16:35 UTC, BaDos commented on tests/travis/functional.sh
> +        echo "Need to fix composer's stuck"
I think this is for the backlog.

2020-02-26 20:53 UTC, BaDos commented on tests/functional/Codeception/TestInfrastructure.php
> +                    'password' => getenv('COMPOSER_MAGENTO_PASSWORD'),
Fixed

2020-02-26 20:53 UTC, BaDos commented on .travis.yml
> +  - if [ $TEST_SUITE == "static-unit" ]; then ./tests/travis/static-unit.sh; fi
Done

2020-02-26 21:18 UTC, oshmyheliuk commented on src/Config/Dist/Generator.php
> +    /**
Where is the description?

2020-02-26 21:19 UTC, oshmyheliuk commented on src/Config/EnvCoder.php
> +     * @param array $variables
Please add description

2020-02-26 21:21 UTC, oshmyheliuk commented on src/Config/Environment/Shared/Reader.php
>      /**
Please add description

2020-02-26 21:25 UTC, BaDos commented on src/Config/Dist/Generator.php
> +    /**
Fixed

2020-02-26 21:27 UTC, BaDos commented on src/Config/EnvCoder.php
> +     * @param array $variables
Done

2020-02-26 21:28 UTC, oshmyheliuk commented on src/Test/Functional/Acceptance/AcceptanceCest.php
> +        $I->runDockerComposeCommand('run deploy cloud-deploy');
Why post-deploy hook is skipped here?

2020-02-26 21:28 UTC, oshmyheliuk commented on src/Test/Integration/_files/.gitignore
> +/*/.docker/config.env
Please add an empty line at the end of file

2020-02-26 21:33 UTC, BaDos commented on src/Test/Functional/Acceptance/AcceptanceCest.php
> +        $I->runDockerComposeCommand('run deploy cloud-deploy');
Added

2020-02-26 21:33 UTC, BaDos commented on src/Config/Environment/Shared/Reader.php
>      /**
Done

2020-02-26 21:34 UTC, BaDos commented on src/Test/Integration/_files/.gitignore
> +/*/.docker/config.env
Added

2020-02-26 21:54 UTC, oshmyheliuk commented on tests/functional/Codeception/MagentoDb.php
> +     * @param $table
Please add description

2020-02-26 21:56 UTC, oshmyheliuk commented on tests/functional/Robo/Tasks/Bash.php
> +class Bash extends DockerCompose\Run
Class description is missed

2020-02-27 01:18 UTC, BaDos commented on tests/functional/Robo/Tasks/Bash.php
> +class Bash extends DockerCompose\Run
Added

2020-02-27 01:18 UTC, BaDos commented on tests/functional/Codeception/MagentoDb.php
> +     * @param $table
Added

2020-02-27 19:53 UTC, oshmyheliuk approved these changes

2020-02-27 20:21 UTC, bbatsche approved these changes

2020-02-27 20:23 UTC, shiftedreality commented
Extended QA will be performed in scope of https://github.com/magento/magento-cloud-docker/pull/162

2020-02-27 20:23 UTC, merged

2020-05-18 19:45 UTC, andriyShevtsov commented
Was done in scope of https://jira.corp.magento.com/browse/MCLOUD-3364