Moved sed substitutions to before the module enables, these were thro…
magento/magento-cloud-docker pull request #129
Opened 2020-01-16 18:58 UTC by aepod

### Description
This solves an issue with the php logs, modules were being enabled while the php ini files that are included in the docker are still in "template mode". The sed commands are moved before the module enables and this makes it so it does not throw errors in log files.

### Fixed Issues (if relevant)
1. magento/magento-cloud-docker#128: PHP Errors in containers upon startup

### Manual testing scenarios
1. These are outlined in the issue. However you will need to be able to test the image build to test this issue. This process is outlined in this Devdocs PR: https://github.com/magento/devdocs/pull/6408

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages

2020-01-17 17:02 UTC, bbatsche requested changes
I think you missed `images/php/{cli|fpm}/docker-entrypoint.sh`, I didn't see them in this PR

2020-01-17 17:02 UTC, bbatsche commented on images/php/7.3-cli/docker-entrypoint.sh
> +[ ! -z "${UPLOAD_MAX_FILESIZE}" ] && sed -i "s/!UPLOAD_MAX_FILESIZE!/${UPLOAD_MAX_FILESIZE}/" /usr/local/etc/php/conf.d/zz-magento.ini
As long as we're modifying these two lines, I think it would be useful to use `$PHP_EXT_DIR` in the file path

2020-01-17 17:05 UTC, aepod commented on images/php/7.3-cli/docker-entrypoint.sh
> +[ ! -z "${UPLOAD_MAX_FILESIZE}" ] && sed -i "s/!UPLOAD_MAX_FILESIZE!/${UPLOAD_MAX_FILESIZE}/" /usr/local/etc/php/conf.d/zz-magento.ini
Added these changes as well.

2020-01-17 17:06 UTC, aepod commented
> I think you missed `images/php/{cli|fpm}/docker-entrypoint.sh`, I didn't see them in this PR

I had yes, I did not see how those were being used until today. I figured out how to run the 
 `./vendor/bin/ece-docker image:generate:php` command.

2020-01-17 17:54 UTC, sikharam-adb submitted a review, later dismissed

2020-01-17 18:56 UTC, bbatsche submitted a review, later dismissed

2020-01-29 22:39 UTC, andriyShevtsov commented
QA aproved

2020-01-29 22:39 UTC, andriyShevtsov commented
@aepod Please look for merge conflicts

2020-01-30 02:23 UTC, aepod commented
Merged from Develop, then fixed merge conflict and repushed my branch. This should solve the merge conflicts.

2020-01-30 16:13 UTC, bbatsche approved these changes

2020-01-30 16:22 UTC, sikharam-adb approved these changes

2020-01-30 16:48 UTC, merged