Custom php.ini from root directory
magento/magento-cloud-docker pull request #130
Opened 2020-01-16 19:56 UTC by aepod

### Description
This change adds a command to the entrypoint.sh which will copy in the php.ini from the root directory. This happens before the php-fpm service or cli command is run. 

This creates zzz-custom-php.ini which is named so it comes last, after all the default docker and magento extension configurations.

Windows/Mac users who are using file synchronization will need to ensure that the file sync is complete or the php.ini will not be copied into the configuration directory.

### Fixed Issues (if relevant)
1. magento/magento-cloud-docker#126: Add possibility to read php.ini

### Manual testing scenarios
1. See https://github.com/magento/devdocs/pull/6408 for details on how to import from custom docker image
2. Once you are building from vendor/magento/magento-cloud-docker/images/php/phpversion/ you should be able to test this.

Please let me know if you have any questions.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages

2020-01-17 16:48 UTC, bbatsche requested changes

2020-01-17 16:48 UTC, bbatsche commented on images/php/cli/docker-entrypoint.sh
> +[ -f "/app/php.ini" ] && cp /app/php.ini ${PHP_EXT_DIR}/zzz-custom-php.ini
Is `$PHP_EXT_DIR` defined on the very next line to this one? So this should go after that.

2020-01-17 16:48 UTC, bbatsche commented on images/php/fpm/docker-entrypoint.sh
> +[ -f "/app/php.ini" ] && cp /app/php.ini ${PHP_EXT_DIR}/zzz-custom-php.ini
Same issue as with `php/cli/docker-entrypoint.sh`

2020-01-17 16:52 UTC, aepod commented on images/php/fpm/docker-entrypoint.sh
> +[ -f "/app/php.ini" ] && cp /app/php.ini ${PHP_EXT_DIR}/zzz-custom-php.ini
Good catch, yes. Fixing that as I am fixing the way this is generated as well. Thanks for the feedback!

2020-01-17 16:59 UTC, aepod commented
@bbatsche I sorted out the order on those, missed that when I brought the changes into the template.

2020-01-17 18:56 UTC, bbatsche approved these changes

2020-01-17 19:39 UTC, oshmyheliuk commented on images/php/cli/docker-entrypoint.sh
> +[ -f "/app/php.ini" ] && cp /app/php.ini ${PHP_EXT_DIR}/zzz-custom-php.ini
Should we check if `PHP_EXT_DIR` exists before copying php.ini file? Or it always exists?

2020-01-17 20:10 UTC, aepod commented on images/php/cli/docker-entrypoint.sh
> +[ -f "/app/php.ini" ] && cp /app/php.ini ${PHP_EXT_DIR}/zzz-custom-php.ini
That one will always exist, comes with the container with it there. This is the reference to it in this shell script, just to keep some of the lines in it a sane length.

2020-01-17 20:13 UTC, oshmyheliuk approved these changes

2020-01-17 20:13 UTC, oshmyheliuk commented on images/php/cli/docker-entrypoint.sh
> +[ -f "/app/php.ini" ] && cp /app/php.ini ${PHP_EXT_DIR}/zzz-custom-php.ini
Ok, thanks for the answer.

2020-01-29 21:20 UTC, andriyShevtsov commented
QA approved

2020-01-29 21:27 UTC, merged