MAGECLOUD-4894  [MTS] Add support of split DB on docker
magento/magento-cloud-docker pull request #161
Opened 2020-02-26 15:23 UTC by arhiopterecs

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-02-26 16:07 UTC, arhiopterecs commented
Previous PR https://github.com/magento/magento-cloud-docker/pull/150

2020-03-02 18:24 UTC, shiftedreality requested changes

2020-03-02 18:24 UTC, shiftedreality commented on src/Config/Relationship.php
> +    private const RELATIONSHIP_DATABASE = 'database';
Please use constants from `ServiceInterface`

2020-03-02 18:24 UTC, shiftedreality commented on src/Config/Source/CliSource.php
> +                foreach ((array)$services as $service) {
`$services` not always array looks like

2020-03-02 18:24 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_DB_QUOTE)) {
It's better to move into separate function

2020-03-04 15:26 UTC, NadiyaS commented on src/Config/Relationship.php
> +    private static $defaultConfiguration= [
add space before **=**

2020-03-04 15:54 UTC, NadiyaS commented on src/Config/Source/CloudSource.php
> +                if (!in_array($name, $possibleNames, true)) {
`$name` may have any value, and do not match with  `$map`. Use $parsedService as was before

2020-03-04 23:13 UTC, arhiopterecs commented on src/Config/Source/CloudSource.php
> +                if (!in_array($name, $possibleNames, true)) {
I do not agree.
If I return the previous implementation, then I can add only one service of one type
I can not add more than one service like MySQL

2020-03-04 23:13 UTC, arhiopterecs commented on src/Config/Relationship.php
> +    private static $defaultConfiguration= [
Done

2020-03-04 23:13 UTC, arhiopterecs commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_DB_QUOTE)) {
I changed the implementation of this part of the code, now it looks better

2020-03-04 23:13 UTC, arhiopterecs commented on src/Config/Source/CliSource.php
> +                foreach ((array)$services as $service) {
Fixed

2020-03-04 23:13 UTC, arhiopterecs commented on src/Config/Relationship.php
> +    private const RELATIONSHIP_DATABASE = 'database';
I deleted these constants and returned the literals as before.

2020-03-09 17:56 UTC, shiftedreality requested changes

2020-03-09 17:56 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_DB_QUOTE)) {
You still have 3 copy-pasted services, this will result in bugs, please separate it into private method

2020-03-09 17:56 UTC, shiftedreality commented on src/Config/Source/SourceInterface.php
> +     * DB QUOTE
Why uppercase? The comment also looks not useful

2020-03-11 20:27 UTC, arhiopterecs commented on src/Config/Source/SourceInterface.php
> +     * DB QUOTE
Yes, It true. Fixed

2020-03-11 23:40 UTC, arhiopterecs commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_DB_QUOTE)) {
fixed

2020-03-17 13:28 UTC, shiftedreality submitted a review, later dismissed

2020-03-17 22:14 UTC, BaDos submitted a review, later dismissed

2020-03-18 18:17 UTC, BaDos approved these changes

2020-03-18 18:19 UTC, shiftedreality approved these changes

2020-03-18 19:45 UTC, mveeramneni commented
QA Approved

2020-03-18 19:48 UTC, merged