MAGECLOUD-4168: Provide an Option to Specify Custom URL for Magento
magento/magento-cloud-docker pull request #163
Opened 2020-03-03 18:40 UTC by oshmyheliuk

### Description
Added possibility to configure hostname and port.

### Fixed Issues (if relevant)
https://magento2.atlassian.net/browse/MAGECLOUD-4168

### Manual testing scenarios
1. Launch Docker environment https://devdocs.magento.com/cloud/docker/docker-mode-production.html
2. Run build compose command with configured host `./vendor/bin/ece-docker build:compose --host=magento2.test`
3. After installation of Magento, check that site is accessible via `magento2.host` not `magento2.docker`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-05 15:15 UTC, shiftedreality requested changes

2020-03-05 15:15 UTC, shiftedreality commented on src/Config/Dist/Generator.php
> +        $host = $config->get(SourceInterface::CONFIG_HOST) ?? Manager::DEFAULT_HOST;
`SourceInterface` should not be used outside of `Config`, please add public methods to `Config`

2020-03-05 15:15 UTC, shiftedreality commented on src/Compose/Manager.php
> +    public const DEFAULT_HOST = 'magento2.docker';
Let's move this to `BaseSource` to be the default value

2020-03-05 15:23 UTC, oshmyheliuk commented on src/Compose/Manager.php
> +    public const DEFAULT_HOST = 'magento2.docker';
This constant was here, I just renamed it.
I don't think that `BaseSource` is a good place for them. I'll move contstants and related methods to the `Config` class.

2020-03-05 15:36 UTC, shiftedreality commented on src/Compose/Manager.php
> +    public const DEFAULT_HOST = 'magento2.docker';
These are default values, which can be changed by aby source, `BaseSource` should be correct

2020-03-05 15:40 UTC, oshmyheliuk commented on src/Config/Dist/Generator.php
> +        $host = $config->get(SourceInterface::CONFIG_HOST) ?? Manager::DEFAULT_HOST;
done

2020-03-05 22:08 UTC, oshmyheliuk commented on src/Compose/Manager.php
> +    public const DEFAULT_HOST = 'magento2.docker';
done

2020-03-06 15:44 UTC, shiftedreality requested changes

2020-03-06 15:44 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +                'Host name'
@meker12 we probably need some task to review all customer-facing texts in Cloud Docker

2020-03-06 15:44 UTC, shiftedreality commented on src/Config/Config.php
> +        return $this->get(SourceInterface::CONFIG_HOST) ?? BaseSource::DEFAULT_HOST;
You don't need ternary here, it must be always by default what you set in `BaseSource`.

Config must not know about sources

2020-03-06 17:12 UTC, oshmyheliuk commented on src/Config/Config.php
> +        return $this->get(SourceInterface::CONFIG_HOST) ?? BaseSource::DEFAULT_HOST;
I didn't set anything in BaseSource, just added constants

2020-03-06 17:15 UTC, oshmyheliuk commented on src/Config/Config.php
> +        return $this->get(SourceInterface::CONFIG_HOST) ?? BaseSource::DEFAULT_HOST;
Updated

2020-03-06 17:24 UTC, shiftedreality approved these changes

2020-03-09 16:31 UTC, arhiopterecs approved these changes

2020-03-10 21:47 UTC, andriyShevtsov commented
QA approved

2020-03-11 13:23 UTC, merged