MAGECLOUD-4164  [Spike] Investigate issue with elasticsearch image on AWS
magento/magento-cloud-docker pull request #165
Opened 2020-03-04 13:21 UTC by arhiopterecs

### Description
Added option --es-env-var for docker-compose.yml file generator. Using this option you can specify environment variables that will be applied when the elasticsearch container starts.

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-09 20:50 UTC, NadiyaS commented on src/Command/BuildCompose.php
> +                "Environment variable for elasticsearch service"
 It would be good to add example for this option.

2020-03-09 21:06 UTC, NadiyaS submitted a review, later dismissed

2020-03-17 23:01 UTC, NadiyaS submitted a review, later dismissed

2020-03-20 18:49 UTC, shiftedreality requested changes

2020-03-20 18:49 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +                "Environment variable for elasticsearch service"
Please use single quotes

2020-03-20 18:49 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +                "Environment variable for elasticsearch service"
I believe it's also optional by default

2020-03-20 18:49 UTC, shiftedreality commented on src/Config/Source/CliSource.php
> +    public const OPTION_ES_EVN_VAR = 'es-env-var';
EVN => ENV

2020-03-20 18:49 UTC, shiftedreality commented on src/Config/Source/CliSource.php
> +    public const OPTION_ES_EVN_VAR = 'es-env-var';
Please use full name, `OPTION_ES_ENVIRONMENT_VARIABLE`

2020-03-20 18:49 UTC, shiftedreality commented on src/Config/Source/SourceInterface.php
> +    public const SERVICES_ES_ENV_VARS = self::SERVICES_ES.'.'.'env-vars';
I would also suggest dropping `env` part, variables are already self-explaining

2020-03-23 20:47 UTC, arhiopterecs commented on src/Config/Source/SourceInterface.php
> +    public const SERVICES_ES_ENV_VARS = self::SERVICES_ES.'.'.'env-vars';
Done

2020-03-23 20:47 UTC, arhiopterecs commented on src/Config/Source/CliSource.php
> +    public const OPTION_ES_EVN_VAR = 'es-env-var';
Done

2020-03-23 20:47 UTC, arhiopterecs commented on src/Command/BuildCompose.php
> +                "Environment variable for elasticsearch service"
Done

2020-03-23 20:53 UTC, arhiopterecs commented
PR was recreated https://github.com/magento/magento-cloud-docker/pull/174

2020-03-23 20:53 UTC, closed without merging