MAGECLOUD-3243: OOTB Docker Startup
magento/magento-cloud-docker pull request #166
Opened 2020-03-10 22:25 UTC by bbatsche

### Description

Added shell script to initialize a fresh Magento Cloud project locally. It will:

1. Install the projects composer dependencies
2. Add `magento2.docker` to the hosts file, if it's not already there.

The script can either be run locally (if Magento Cloud Docker has already been installed as a dependency) or via piping a curl request into bash:

```bash
curl https://raw.githubusercontent.com/magento/magento-cloud-docker/MAGECLOUD-3243/bin/init-docker.sh | bash
```

Optional flags can be passed to select which version of PHP to use or disable adding the domain to /etch/hosts:

```bash
curl https://raw.githubusercontent.com/magento/magento-cloud-docker/MAGECLOUD-3243/bin/init-docker.sh | bash -s -- --php 7.3 --host no
```

### Fixed Issues (if relevant)

[MAGECLOUD-3243](https://magento2.atlassian.net/browse/MAGECLOUD-3243)

### Manual testing scenarios

Cd to a Magento Cloud project
Use the above example to run the script via curl
If the domain is already in /etc/hosts, a warning should be emitted and no duplicate entries should be added

Test that only supported flags may be passed
Test that `--host` or `-t` only accepts "boolean" values
Test that `--php` or `-p` only accepts valid version numbers (e.g. `7.1`. There is no validation on whether the version number is a *real* PHP version, so for example the script will allow you to pass `8.4`)

### Future Additions

1. Ability to add the TLS container's cert to the local machine's trusted keychain. This was skipped because it would require the containers to be booted and I was concerned about wanting the user to have more flexibility there (this could be resolved with more research)
2. Ability to override the default domain with something else. I skipped this because I didn't want to get the user into an inconsistent state where `/etc/hosts` had a custom domain, but their generated configs had the default one. At this time, using a custom domain is probably best done fully manually so the user is aware of what they're doing. If customizing those values becomes simpler in the future, it may be easy to automate these steps through this script.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-11 14:00 UTC, shiftedreality requested changes

2020-03-11 14:00 UTC, shiftedreality commented on bin/init-docker.sh
> +    if grep -Eq "^\s*\d+\.\d+\.\d+\.\d+\s+${DOMAIN}$" /etc/hosts; then
This may be not compatible with Windows. Alos `.bat` entry point is needed for Windows systems

2020-03-11 14:00 UTC, shiftedreality commented on bin/init-docker.sh
> +    docker run --rm -e "MAGENTO_ROOT=/app" -v "$(pwd)":/app -v ~/.composer/cache:/root/.composer/cache "magento/magento-cloud-docker-php:${PHP_VERSION}-cli" composer install --ansi
This PHP binary is outdated, we should use the same version as we generate `docker-compose.yml`
See: src/Service/ServiceFactory.php:166

2020-03-11 14:00 UTC, shiftedreality commented on bin/init-docker.sh
> +DOMAIN="magento2.docker"
We support custom domains, would make sense to add this option

2020-03-11 14:00 UTC, shiftedreality commented on bin/init-docker.sh
> +PHP_VERSION="7.2"
I would recommend making this a required argument since default value will be outdated pretty soon

2020-03-11 19:17 UTC, bbatsche commented on bin/init-docker.sh
> +DOMAIN="magento2.docker"
Kk. Like I said I was on the fence on it, but I think it's a worthwhile addition

2020-03-11 19:18 UTC, bbatsche commented on bin/init-docker.sh
> +PHP_VERSION="7.2"
Maybe we could bump it to 7.3? Since this is a first-run script, I wanted to make it as simple and seamless as possible, so no required arguments.

2020-03-11 19:22 UTC, bbatsche commented on bin/init-docker.sh
> +    if grep -Eq "^\s*\d+\.\d+\.\d+\.\d+\s+${DOMAIN}$" /etc/hosts; then
There's a Windows hosts file, just under a slightly different path. I'm doing some research on how to make sure it's updated correctly. In theory, this script could just be piped to bash if the user has Windows Subsystem for Linux installed.

Otherwise Windows batch scripting is outside my immediate experience and I don't have a super easy way to test it.

2020-03-11 19:48 UTC, bbatsche commented on bin/init-docker.sh
> +PHP_VERSION="7.2"
Alternatively, the script could attempt a naive grep of `.magento.app.yaml` or `.magento.docker.yaml` to select whatever version to user has already configured, but that would be more complex (and prone to error)

2020-03-12 20:52 UTC, michaelcasey316 submitted a review, later dismissed

2020-03-13 14:07 UTC, shiftedreality submitted a review, later dismissed

2020-03-13 14:07 UTC, shiftedreality commented on bin/init-docker.sh
> +    if grep -Eq "^\s*\d+\.\d+\.\d+\.\d+\s+${DOMAIN}$" /etc/hosts; then
We can suggest using WSL for this

2020-03-13 14:07 UTC, shiftedreality commented on bin/init-docker.sh
> +PHP_VERSION="7.2"
Agree, let's not make it to complex for now

2020-03-16 03:40 UTC, andriyShevtsov commented
QA approved

2020-03-16 03:49 UTC, andriyShevtsov commented
I have some question about naming. Asked in slack

2020-03-19 20:16 UTC, shiftedreality approved these changes

2020-03-20 02:29 UTC, andriyShevtsov commented
QA approved

2020-03-20 17:04 UTC, michaelcasey316 approved these changes

2020-03-20 17:08 UTC, merged