Add Multi-website Support into Cloud Docker
magento/magento-cloud-docker pull request #167
Opened 2020-03-12 06:59 UTC by mohanelamurugan

### Description
Added multi website support in cloud docker(Appended magneto-vars.php to php.ini) .

1. Start the magento cloud docker, set to developer deploy mode following this tutorial: https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-config.html
2. Set up a new website, store, store view and use this tutorial to set up a new website: https://devdocs.magento.com/guides/v2.3/cloud/project/project-multi-sites.html
3. Assuming we plan to have http://second.magento2.docker/ for the new website that we are adding, Add second.magento2.docker to hosts file.
4. Visit http://second.magento2.docker/

### Fixed Issues (if relevant)

[MCD-104](https://github.com/magento/magento-cloud-docker/issues/104)

### Manual testing scenarios

1. Add both websites base url to hosts
2. Visit each website's URL from browser
3. Secondary website URL should redirect to the secondary website instead of redirecting to the base website's URL.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-13 14:09 UTC, shiftedreality requested changes

2020-03-13 14:09 UTC, shiftedreality commented on images/php/7.1-cli/etc/php-cli.ini
> +auto_append_file = /app/magento-vars.php
Please add new line

2020-03-13 14:09 UTC, shiftedreality commented on images/php/fpm/etc/php-fpm.ini
> +auto_append_file = /app/magento-vars.php
Please add new line

2020-03-16 12:19 UTC, mohanelamurugan commented on images/php/7.1-cli/etc/php-cli.ini
> +auto_append_file = /app/magento-vars.php
Added. Pls review again

2020-03-16 13:44 UTC, NadiyaS commented on images/php/fpm/etc/php-fpm.ini
> +ff
Please remove this

2020-03-16 13:45 UTC, NadiyaS commented on images/php/cli/etc/php-cli.ini
> +git stataus
please remove this line

2020-03-16 13:53 UTC, shiftedreality approved these changes

2020-03-16 13:55 UTC, NadiyaS approved these changes

2020-03-16 14:35 UTC, andriyShevtsov commented
Created internal task MAGECLOUD-5584

2020-03-17 14:28 UTC, shiftedreality commented
To run in Production mode:

1. create file `docker-compose.override.yaml`:

```yaml
version: '2.1'
services:
  web:
    volumes:
      - './magento-vars.php:/app/magento-vars.php:ro'
  build:
    volumes:
      - './magento-vars.php:/app/magento-vars.php:ro'
  deploy:
    volumes:
      - './magento-vars.php:/app/magento-vars.php:ro'
```

2020-03-18 13:22 UTC, andriyShevtsov commented
@shiftedreality Please take a look. With production mode and  `docker-compose.override.yaml` I have error  
`Fatal error: Cannot redeclare isHttpHost() (previously declared in /app/magento-vars.php:20) in /app/magento-vars.php on line 20`

2020-03-18 15:08 UTC, shiftedreality commented
@andriyShevtsov it looks like the trick with `docker-compose.override.yml` is not needed. This issue somehow relates to Docker itself and can be avoided by simple adjustment:

```php
if (!function_exists('isHttpHost')) {
    function isHttpHost($host)
    {
        if (!isset($_SERVER['HTTP_HOST'])) {
            return false;
        }
        return strpos(str_replace('---', '.', $_SERVER['HTTP_HOST']), $host) === 0;
    }
}
```

I'll add this note as part of DevDocs PR.

QA approved overall.

2020-03-18 15:17 UTC, shiftedreality commented
I just realized it will break the default behavior. 

@mohanelamurugan could you please check this PR in Production mode if you have the same problem?

2020-03-18 17:31 UTC, mohanelamurugan commented
Sure @shiftedreality , Let mw check this

2020-03-19 11:57 UTC, mohanelamurugan commented
@shiftedreality 
I tested it in production mode. I was able to run deploys, post deploys, cache clean, index:reindex as well.
Also multi site redirections are also working fine.
The first one runs in the URL magento2.docker whereas the other one is second.magento2.docker.
Also from the attached image below, You can find that the setup is running in production mode.
PFA 
<img width="1440" alt="Screen Shot 2020-03-19 at 4 45 47 PM" src="https://user-images.githubusercontent.com/13690499/77064990-798f3d80-6a06-11ea-8fe0-fa5b3138fab2.png">
<img width="1440" alt="Screen Shot 2020-03-19 at 4 45 53 PM" src="https://user-images.githubusercontent.com/13690499/77065001-7dbb5b00-6a06-11ea-9b2a-355a00a507ee.png">
<img width="1440" alt="Screen Shot 2020-03-19 at 5 18 08 PM" src="https://user-images.githubusercontent.com/13690499/77065004-7e53f180-6a06-11ea-820e-ca1c1e90e4cc.png">

2020-03-19 13:45 UTC, andriyShevtsov commented
Thank you. Most likely that issue was not related to your PR. QA approved.

2020-03-19 13:48 UTC, merged