Fix for conflicting volumes - #43
magento/magento-cloud-docker pull request #168
Opened 2020-03-12 07:44 UTC by G-Arvind

### Description

Currently, the Magento Cloud Docker uses magento-sync volume and other volumes with no prefix for project. This causes collision and conflict when trying to switch projects.

To solve this, it should use a prefix for all volumes, this should probably be from .magento.app.yaml or .magento.docker.yaml and is by default set as follows:name: mymagento

This would then create volumes as mymagento-magento-sync and mymagento-magento-db. This allows projects to set this name and have it generate volumes that can persist.

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#43: Give us the ability to have multiple projects with different volumes (Prefixed the volume name with the name that is provided in .magento.app.yaml or .magent.docker.yaml)
2. Made Name as a required field. (So that the volumes can prefixed with the given name)

### Manual testing scenarios

1) Add .magento.app.yaml or .magento.docker.yaml (with name field included).
2) Run ./vendor/bin/ece-docker build:compose --mode="developer" (OR) ./vendor/bin/ece-docker build:compose 
3) docker-compose.yaml will be generated.
4) Verify that volume names are prefixed with Name given in .magento.app.yaml or .magento.docker.yaml
5) Verify Multilple projects with different volumes are working.
     
- Mount a project using docker environment
- After that, try to create another one using the same architecture

7) Both projects should work with no error
8) if no Name is provided in .magento.app.yaml or .magento.docker.yaml an  exception will be thrown "Name could not be parsed."

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-12 15:53 UTC, bbatsche requested changes
Simple whitespace fix needed

2020-03-12 15:53 UTC, bbatsche commented on src/Compose/ProductionBuilder.php
> +
Remove this extra whitespace...

2020-03-12 15:53 UTC, bbatsche commented on src/Compose/ProductionBuilder.php
> -
... and add this one back. Looks like there shouldn't be any changes to this file

2020-03-13 14:06 UTC, bbatsche submitted a review, later dismissed

2020-03-13 19:50 UTC, bbatsche submitted a review, later dismissed

2020-03-16 17:46 UTC, arhiopterecs commented on src/Compose/DeveloperBuilder.php
>          $manager->setVolumes([
I think it would be better if the concatenation of the prefix and volumes fit inside the "Manager" object
Thus, you would not need to add a prefix every time

2020-03-17 13:52 UTC, G-Arvind commented on src/Compose/DeveloperBuilder.php
>          $manager->setVolumes([
I started to work on your comment but I have a few questions, this change introduces 4 if statements inside setVolumes() alone is this fine?, other than this should addService() and update service() present in Manager Class be able to prefix the volumes, or directly prefixing them in DeveloperBulider /ProductionBuilder is enough(Current Approach)?

Example snippet: like this 4cases should be done inside setVolumes()
```
if(array_key_exists( "magento-db", $volumes)) 
{
        $oldkey= "magento-db";
        $keys = array_keys($volumes);
        $keys[array_search($oldkey, $keys)] = $this->config->getName().'-'.$oldkey;
        $volumes= array_combine($keys, $volumes);
        $extConfig["volumes"]=$volumes;
}
```

2020-03-19 15:32 UTC, arhiopterecs commented on src/Compose/DeveloperBuilder.php
>          $manager->setVolumes([
The main idea of ​​my proposal was that prefix concatenation be implemented in the Manager class
After that, in the Manager, we can add a method to get the mounts for a specific service.

Now, in order to expedite the delivery, I suggest for now just updating the branch without rework.

2020-03-19 15:36 UTC, arhiopterecs approved these changes

2020-03-19 17:19 UTC, bbatsche approved these changes

2020-03-23 03:16 UTC, andriyShevtsov commented
I suppose we should automatically change port. Because port 80  will be occupied in case of few docker projects

2020-03-23 03:20 UTC, andriyShevtsov commented
The same for TLS (port 443)

2020-03-23 12:34 UTC, aepod commented
This ticket only covers conflicting volumes.

2020-03-23 18:49 UTC, andriyShevtsov commented
Test:

1. Have 2 projects
2. Name prefix the same
3. Start first project
4. Ensure all works
5. Stop project with docker-compose stop
6. Complete steps 3-4 for 2nd project

Approved

2020-03-23 18:56 UTC, merged