MAGECLOUD-4919: Ability to run ece-tools on custom github source code
magento/magento-cloud-docker pull request #170
Opened 2020-03-12 20:51 UTC by oshmyheliuk

### Description
https://magento2.atlassian.net/browse/MAGECLOUD-4919

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-13 15:31 UTC, shiftedreality requested changes

2020-03-13 15:31 UTC, shiftedreality commented on src/Config/Source/SourceInterface.php
> +    public const INSTALLATION_TYPE = 'install.type';
Looks like the new line is missed

2020-03-13 15:31 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +                'Sets that magento installed from git',
magento must be uppercase, please also rephrase this, as it's confusing

2020-03-13 15:35 UTC, oshmyheliuk commented on src/Command/BuildCompose.php
> +                'Sets that magento installed from git',
Yeah, it was a description of the previous implementation. Thanks, I'll fix

2020-03-13 18:46 UTC, oshmyheliuk commented on src/Command/BuildCompose.php
> +                'Sets that magento installed from git',
updated

2020-03-13 18:46 UTC, oshmyheliuk commented on src/Config/Source/SourceInterface.php
> +    public const INSTALLATION_TYPE = 'install.type';
added

2020-03-13 20:44 UTC, shiftedreality approved these changes

2020-03-16 14:25 UTC, BaDos approved these changes

2020-03-16 16:38 UTC, BaDos commented
@oshmyheliuk Plz cover by FT

2020-03-16 17:30 UTC, oshmyheliuk commented
will be covered in this task https://magento2.atlassian.net/browse/MAGECLOUD-5592

2020-03-17 16:30 UTC, mveeramneni commented
QA Approved

2020-03-17 16:35 UTC, mveeramneni commented
QA Approved

2020-03-17 16:42 UTC, merged