Fix for multiple mysql instance error-#169
magento/magento-cloud-docker pull request #181
Opened 2020-03-30 14:48 UTC by G-Arvind

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#169: Docker compose fails if multiple users for mysql configured

### Manual testing scenarios

1.Add Multiple mysql users in services.yml, as described here https://devdocs.magento.com/cloud/project/project-conf-files_services-mysql.html
```
mysql:
    type: mysql:10.2
    disk: 2048
    configuration:
        schemas:
            - main
        endpoints:
            admin:
                default_schema: main
                privileges:
                    main: admin
            reporter:
                privileges:
                    main: ro

redis:
    type: redis:5.0

elasticsearch:
    type: elasticsearch:6.5
    disk: 1024
```
2.Add the endpoints defined, to the relationships property of the .magento.app.yaml file. 
```
relationships:
    database: "mysql:admin"
    databasereporter: "mysql:reporter"
```
3. Run ./vendor/bin/ece-docker build:compose --mode="developer"

**Expected result**
Docker build is successful

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-03-30 17:29 UTC, michaelcasey316 requested changes

2020-03-30 17:29 UTC, michaelcasey316 commented on src/Config/Source/CloudSource.php
> +                if ($repository->has(self::SERVICES . '.' . $service) && $service != "mysql") {
```suggestion
                if ($repository->has(self::SERVICES . '.' . $service) && $service != ServiceInterface::SERVICE_DB) {
```

2020-03-30 18:20 UTC, michaelcasey316 approved these changes

2020-04-05 02:00 UTC, arhiopterecs approved these changes

2020-04-07 18:01 UTC, mveeramneni commented
Tested this PR with magento 2.3.4 in developer mode and encountered below error
`2020-04-07 15:46:50] NOTICE: Starting install.
[2020-04-07 15:46:50] INFO: Installing Magento.
[2020-04-07 15:46:50] INFO: Initializing routes.
In Shell.php line 86:
  The command "/bin/bash -c "set -o pipefail; php ./bin/magento setup:install -n --session-save=db --cleanup-database --use-secure-admin=1 --use-rewrites=1 --ansi --no-interaction --currency='USD' --
  base-url='http://magento2.docker/' --base-url-secure='https://magento2.docker/' --backend-frontname='admin' --language='en_US' --timezone=America/Los_Angeles --db-host='db' --db-name='magento2' --d
  b-user='magento2' --db-password='******' --admin-user='admin' --admin-firstname='Admin' --admin-lastname='Username' --admin-email='admin@example.com' --admin-password='******' | tee -a /app/var/log
  /install_upgrade.log"" failed. In ErrorHandler.php line 61:
    Warning: Declaration of Dotdigitalgroup\Email\Helper\Data\Interceptor::log(
    $data) should be compatible with Dotdigitalgroup\Email\Helper\Data::log($da
    ta, $extra = Array) in /app/generated/code/Dotdigitalgroup/Email/Helper/Dat
    a/Interceptor.php on line 7`
Discussed with @shiftedreality and decided it's magento bug.

Tested with magento 2.3.2 version in developer mode and build is successful.

QA Approved

2020-04-07 18:50 UTC, merged