Add cache clearing to CLI
magento/magento-cloud-docker pull request #184
Opened 2020-04-01 11:09 UTC by mohanelamurugan

Add cache clearing to CLI

### Description

For repetitive tasks during development. It is often necessary to clear cache from outside the Magento application, So I have added a CLI method to clear redis cache

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#179: Add cache clearing to CLI

### Manual testing scenarios

1. Run docker-compose run deploy redis-clean to clean redis cache outside of Magento application

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-03 21:17 UTC, bbatsche requested changes
I'm not sure about the utility of this script or the logic of putting it in the PHP images. Ideally it would be in the `redis` image, but we are using essentially the stock image from Docker.

Ultimately though, this same functionality could be accomplished by running

```bash
docker-compose exec redis redis-cli -h redis FLUSHALL
```

so I'm not sure this solution is much better.

2020-04-03 21:17 UTC, bbatsche commented on images/php/cli/bin/redis-clean
> +exec redis redis-cli FLUSHALL
I think there may be some confusion here. `exec redis...` leads me to believe you're trying to run `redis-cli` in the `redis` container, however in a bash script such as this the `exec` statement completely different from `docker exec`.

In addition, `redis-cli` needs to know the host it should be communicating with (even when running from within the `redis` container). So you will need to add `-h redis` to the `redis-cli` call.

2020-04-06 16:34 UTC, michaelcasey316 commented
Putting helper commands in the `bin/` folder would be new and different. We already have helper commands in `dist/bin/magento-docker`. Perhaps it would be better to move flush-redis and flush-varnish to `dist/bin/magento-docker` with the rest of the helper commands. What do you all think?

2020-04-06 16:49 UTC, aepod commented
If this approach is taken, we also need to modify composer.json to include
these into bin/ directory when composer install is run.

I think this is a better approach.

On Mon, Apr 6, 2020 at 12:34 PM Michael Casey <notifications@github.com>
wrote:

> Putting helper commands in the bin/ folder would be new and different. We
> already have helper commands in dist/bin/magento-docker. Perhaps it would
> be better to move flush-redis and flush-varnish to dist/bin/magento-docker
> with the rest of the helper commands. What do you all think?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento-cloud-docker/pull/184#issuecomment-609902296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA6NE77EECMWMJC3IK6NRDRLIACHANCNFSM4LYZGRHA>
> .
>

2020-04-06 17:36 UTC, michaelcasey316 commented
> If this approach is taken, we also need to modify composer.json to include these into bin/ directory when composer install is run. I think this is a better approach.

We actually already do this mapping, see https://github.com/magento/magento-cloud-docker/blob/4ca9932f51234d9359f78a6f5676fd91aca40427/composer.json#L88

2020-04-06 19:12 UTC, aepod commented
Exactly, great catch. Mohan will update.

On Mon, Apr 6, 2020 at 1:36 PM Michael Casey <notifications@github.com>
wrote:

> If this approach is taken, we also need to modify composer.json to include
> these into bin/ directory when composer install is run. I think this is a
> better approach.
>
> We actually already do this mapping, see
> https://github.com/magento/magento-cloud-docker/blob/4ca9932f51234d9359f78a6f5676fd91aca40427/composer.json#L88
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento-cloud-docker/pull/184#issuecomment-609935365>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA6NE24F2KUKWBE4A72VHDRLIHLRANCNFSM4LYZGRHA>
> .
>

2020-04-07 05:52 UTC, mohanelamurugan commented
> I'm not sure about the utility of this script or the logic of putting it in the PHP images. Ideally it would be in the `redis` image, but we are using essentially the stock image from Docker.
> 
> Ultimately though, this same functionality could be accomplished by running
> 
> ```shell
> docker-compose exec redis redis-cli -h redis FLUSHALL
> ```
> 
> so I'm not sure this solution is much better.

This approach has been changed now.

2020-04-07 06:00 UTC, mohanelamurugan commented
> Exactly, great catch. Mohan will update.
> […](#)

@michaelcasey316 Can you check now pls. I have made the changes to move shell files to dist/bin/ directory

FYI
@aepod

2020-04-07 15:58 UTC, michaelcasey316 commented
This could work, as now `flush-varnish` and `flush-redis` will be in the `bin/` directory of your Magento Cloud project. However, I'm concerned about proliferation of files in that folder, and also with confusing people that aren't using Cloud Docker. Even if you're not using Cloud Docker, you'll still see `flush-redis` and `flush-varnish` in your `bin/` directory, which could be quite confusing when those fail to perform their stated actions. 

Maybe we can put these two commands inside of the shell script `dist/bin/magento-docker`. Then all the Cloud Docker commands would be in the same place.

2020-04-08 08:01 UTC, mohanelamurugan commented
> proliferation



> This could work, as now `flush-varnish` and `flush-redis` will be in the `bin/` directory of your Magento Cloud project. However, I'm concerned about proliferation of files in that folder, and also with confusing people that aren't using Cloud Docker. Even if you're not using Cloud Docker, you'll still see `flush-redis` and `flush-varnish` in your `bin/` directory, which could be quite confusing when those fail to perform their stated actions.
> 
> Maybe we can put these two commands inside of the shell script `dist/bin/magento-docker`. Then all the Cloud Docker commands would be in the same place.

Understood. I have moved the files to `dist/bin/magento-docker`

2020-04-08 17:49 UTC, michaelcasey316 submitted a review, later dismissed

2020-04-08 18:41 UTC, bbatsche submitted a review, later dismissed

2020-04-13 06:09 UTC, mohanelamurugan commented
@bbatsche @michaelcasey316 : A merge conflict has been resolved. Can you guys please
re review this PR ?

2020-04-13 16:39 UTC, michaelcasey316 approved these changes

2020-04-13 16:58 UTC, bbatsche approved these changes

2020-04-16 17:06 UTC, mveeramneni commented
QA Approved

2020-04-16 17:14 UTC, merged