Healthchecks for nginx and php fpm
magento/magento-cloud-docker pull request #188
Opened 2020-04-07 14:21 UTC by VisanthSampath

### Description

 Add container health checks for Nginx and PHP-FPM.

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#116: Add additional health checks.

### Manual testing scenarios

1. Build Nginx and PHP-FPM containers.
2. Run ./vendor/bin/ece-docker build:compose --mode="developer".
3. Run docker-compose up
4. Check if the Nginx and FPM containers are healthy.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-07 16:21 UTC, michaelcasey316 reviewed
The code looks good. I have one question though, does `bin/ece-docker image:generate:php` need to be run to generate the appropriate configs for each of the PHP-FPM versions? For example, `images/php/7.1-fpm/etc/php-fpm.conf`, `images/php/7.2-fpm/etc/php-fpm.conf`, etc.

2020-04-07 17:54 UTC, shiftedreality requested changes

2020-04-07 17:54 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +            $this->serviceFactory->create(
This should be part of the image, like ES

2020-04-07 17:54 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +                    self::SERVICE_HEALTHCHECK => [
This also should go to image

2020-04-07 17:54 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +                    self::SERVICE_HEALTHCHECK => [
You can use `depends` like `build` or `deploy` container

2020-04-08 10:43 UTC, VisanthSampath commented on src/Compose/ProductionBuilder.php
> +                    self::SERVICE_HEALTHCHECK => [
@shiftedreality The changes have been made. The health checks are now running inside the container.

2020-04-08 10:45 UTC, VisanthSampath commented
> The code looks good. I have one question though, does `bin/ece-docker image:generate:php` need to be run to generate the appropriate configs for each of the PHP-FPM versions? For example, `images/php/7.1-fpm/etc/php-fpm.conf`, `images/php/7.2-fpm/etc/php-fpm.conf`, etc.

@michaelcasey316 The command has been run and committed those files under this pull request.

2020-04-09 15:08 UTC, michaelcasey316 commented
> > The code looks good. I have one question though, does `bin/ece-docker image:generate:php` need to be run to generate the appropriate configs for each of the PHP-FPM versions? For example, `images/php/7.1-fpm/etc/php-fpm.conf`, `images/php/7.2-fpm/etc/php-fpm.conf`, etc.
> 
> @michaelcasey316 The command has been run and committed those files under this pull request.

I'm looking at the files changed, and I don't see the versioned PHP images updated. Perhaps they were overwritten by one of your force pushes?

2020-04-10 14:53 UTC, VisanthSampath commented
> > > The code looks good. I have one question though, does `bin/ece-docker image:generate:php` need to be run to generate the appropriate configs for each of the PHP-FPM versions? For example, `images/php/7.1-fpm/etc/php-fpm.conf`, `images/php/7.2-fpm/etc/php-fpm.conf`, etc.
> > 
> > 
> > @michaelcasey316 The command has been run and committed those files under this pull request.
> 
> I'm looking at the files changed, and I don't see the versioned PHP images updated. Perhaps they were overwritten by one of your force pushes?

@michaelcasey316 it was my bad.  They might have overwritten by force pushes. Added the versioned PHP-FPM files now.

2020-04-10 17:46 UTC, michaelcasey316 approved these changes

2020-04-14 15:44 UTC, shiftedreality approved these changes

2020-04-15 19:53 UTC, mveeramneni commented
QA Approved

2020-04-16 13:48 UTC, merged