Add DB access to the CLI
magento/magento-cloud-docker pull request #192
Opened 2020-04-08 12:48 UTC by G-Arvind

### Description

For repetitive tasks during development, It is more convenient to access the DB from CLI, so I have added a CLI method for command-line access to the DB.

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#180: Add DB access to the CLI

### Manual testing scenarios

1. Run ``` ./bin/magento-docker mysql``` to access DB console.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-08 15:08 UTC, shiftedreality requested changes

2020-04-08 15:08 UTC, shiftedreality commented on dist/bin/magento-docker
> +  mysql             access to mysql DB
It's better to name it ece-db, to be more generic and support both MariaDB and Mysql

2020-04-08 15:08 UTC, shiftedreality commented on dist/bin/magento-docker
> +    mysql)
`ece-db`

2020-04-08 15:08 UTC, shiftedreality commented on dist/bin/magento-docker
> +        docker-compose exec db sh -c 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE "$@"'
Please use `run --rm` instead

2020-04-09 11:54 UTC, aepod commented on dist/bin/magento-docker
> +        docker-compose exec db sh -c 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE "$@"'
This creates a new container, which will not have access to the DB, which is why he was using exec, not `run --rm`

2020-04-09 12:46 UTC, G-Arvind commented on dist/bin/magento-docker
> +  mysql             access to mysql DB
Changed to ece-db

2020-04-09 14:56 UTC, oshmyheliuk approved these changes

2020-04-09 15:49 UTC, shiftedreality commented on dist/bin/magento-docker
> +        docker-compose exec db sh -c 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE "$@"'
Cool, makes sense them

2020-04-09 15:49 UTC, shiftedreality approved these changes

2020-04-10 17:02 UTC, andriyShevtsov commented
QA approved

2020-04-10 18:16 UTC, merged