Fix for composer running out of memory in container
magento/magento-cloud-docker pull request #197
Opened 2020-04-15 11:04 UTC by mohanelamurugan

### Description

This fixes composer running out of memory when installing multiple packages through cloud docker

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#191: Composer runs out of memory in container

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-16 14:01 UTC, shiftedreality requested changes

2020-04-16 14:01 UTC, shiftedreality commented on images/php/7.1-cli/etc/php-cli.ini
> +composer_memory_limit = -1
This probably should be an environment variable in `Dockerfile`

2020-04-16 15:54 UTC, michaelcasey316 requested changes
I agree with @shiftedreality. Having this adjustable in docker-compose.yml or the Dockerfile would be ideal.

2020-04-16 16:56 UTC, aepod commented
I suppose it is fair to say that if we are setting a default in the
containers, we should expose it in the Dockerfile so that it can be used
from docker commands easily.

If we had a styleguide, this would be a good rule it seems. Thanks for the
feedback @michaelcasey316 and @shiftedreality
<https://github.com/shiftedreality>.

On Thu, Apr 16, 2020 at 11:55 AM Michael Casey <notifications@github.com>
wrote:

> *@michaelcasey316* requested changes on this pull request.
>
> I agree with @shiftedreality <https://github.com/shiftedreality>. Having
> this adjustable in docker-compose.yml or the Dockerfile would be ideal.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento-cloud-docker/pull/197#pullrequestreview-394773966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA6NE54M4ZLLNS6BVIJ2W3RM4S5LANCNFSM4MIPMCKA>
> .
>

2020-04-17 08:58 UTC, mohanelamurugan commented on images/php/7.1-cli/etc/php-cli.ini
> +composer_memory_limit = -1
I have added an environment variable in the `Dockerfile` and used it in ini now.

2020-04-20 05:48 UTC, mohanelamurugan commented
@shiftedreality Requested changes are implemented.

2020-04-22 13:52 UTC, shiftedreality requested changes

2020-04-22 13:52 UTC, shiftedreality commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
This is probably not valid syntax, is there any sample of this notation?

2020-04-22 13:52 UTC, shiftedreality commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
This is probably not valid syntax, is there any sample of this notation? I'm also not sure of `composer_memory_limit` exists

2020-04-22 14:59 UTC, mohanelamurugan commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
@shiftedreality  Here in https://github.com/magento/magento-cloud-docker/blob/develop/images/php/fpm/etc/php-fpm.ini , it have been used as `memory_limit = !PHP_MEMORY_LIMIT! ; Variable: PHP_MEMORY_LIMIT ` . I did similar implementation.

2020-04-22 15:00 UTC, mohanelamurugan commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
@shiftedreality  Here in https://github.com/magento/magento-cloud-docker/blob/develop/images/php/fpm/etc/php-fpm.ini , it have been used as `memory_limit = !PHP_MEMORY_LIMIT! ; Variable: PHP_MEMORY_LIMIT ` . I did similar implementation.

2020-04-23 15:38 UTC, shiftedreality commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
Yes, but `memory_limit` is supported in `php.ini`, which is not a case with `composer_memory_limit`

Please revert all changes. ENV variable should be enough according to https://getcomposer.org/doc/articles/troubleshooting.md

2020-04-23 17:42 UTC, mohanelamurugan commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
okay, Sure. Its clear now. I will leave the environment variable and remove the ini changes

2020-04-23 17:51 UTC, mohanelamurugan commented on images/php/cli/etc/php-cli.ini
> +composer_memory_limit = COMPOSER_MEMORY_LIMIT
I have fixed it now. Can you please review it

2020-04-23 17:52 UTC, mohanelamurugan commented
@shiftedreality Now only the composer memory limit is set as environment variable without any ini file changes.

2020-04-23 21:48 UTC, michaelcasey316 approved these changes

2020-04-27 15:35 UTC, shiftedreality approved these changes

2020-04-28 03:20 UTC, andriyShevtsov commented
@shiftedreality Maybe make sense to merge this PR first https://github.com/magento/magento-cloud-docker/pull/198 and update current PR? Otherwise we should  create task task to update COMPOSER_MEMORY_LIMIT -1 for php 7.4 or fix memory limit  in PR with php 7.4 image.

2020-04-28 16:28 UTC, andriyShevtsov commented
Approved

2020-04-28 16:33 UTC, merged