Magecloud 194
magento/magento-cloud-docker pull request #198
Opened 2020-04-16 08:11 UTC by mohanelamurugan

### Description

Added Php 7.4 support for cloud docker

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#194: Add PHP 7.4 images

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-16 16:05 UTC, shiftedreality requested changes

2020-04-16 16:05 UTC, shiftedreality commented on src/Compose/Php/ExtensionResolver.php
> +                '>=7.4' => [
Previous entry should be closed on `<7.4` since you currently install 2 versions of xdebug for PHP 7.4

2020-04-16 16:05 UTC, shiftedreality commented on images/php/7.4-fpm/Dockerfile
> +  xdebug-2.7.1 \
Should be only 2.9.3

2020-04-17 05:05 UTC, mohanelamurugan commented on src/Compose/Php/ExtensionResolver.php
> +                '>=7.4' => [
@shiftedreality  Changed the previous entry to Added php 7.4 image

2020-04-17 05:06 UTC, mohanelamurugan commented on images/php/7.4-fpm/Dockerfile
> +  xdebug-2.7.1 \
@shiftedreality 
Has been changed after correcting the ExtensionResolver.php and generating php images again

2020-04-17 05:07 UTC, mohanelamurugan commented
@shiftedreality Requested changes are implemented.

2020-04-17 15:02 UTC, arhiopterecs submitted a review, later dismissed

2020-04-20 13:27 UTC, shiftedreality approved these changes

2020-04-20 20:57 UTC, mveeramneni commented
`Mounikas-MacBook-Pro:MC-5806 veeramne$ docker build -t test/php:7.4-cli ../MC-5806/images/php/7.4-cli
Sending build context to Docker daemon  26.62kB
Step 1/38 : FROM php:7.4-cli-stretch
manifest for php:7.4-cli-stretch not found: manifest unknown: manifest unknown`

Can't build php 7.4 image locally

2020-04-21 12:35 UTC, mohanelamurugan commented
> `Mounikas-MacBook-Pro:MC-5806 veeramne$ docker build -t test/php:7.4-cli ../MC-5806/images/php/7.4-cli Sending build context to Docker daemon 26.62kB Step 1/38 : FROM php:7.4-cli-stretch manifest for php:7.4-cli-stretch not found: manifest unknown: manifest unknown`
> 
> Can't build php 7.4 image locally

There are issues with 7.4 images and I am working on it. The issues are as follows:-

1. php:7.4-cli-stretch is not yet available
**Solution:**: Need to change the docker to use php:7.4-cli image instead

2. Error: unrecognized options: --with-png-dir, --with-jpeg-dir, --with-freetype-dirSolution:  **Solution:**: Changing the line 

`docker-php-ext-configure gd --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr
`
into
`docker-php-ext-configure gd --with-freetype --with-jpeg`

 

3. We need to remove extensions such as zip --with-libzip, imap and recode 

4. Ioncube is not supported with the php 7.4
**Solution:** Remove ioncube for 7.4

2020-04-22 13:55 UTC, shiftedreality requested changes

2020-04-22 13:55 UTC, shiftedreality commented on images/php/7.4-cli/Dockerfile
> +FROM php:7.4-cli-stretch
It looks like PHP updated distro, we should use "buster" here: 

Missing: https://hub.docker.com/_/php?tab=tags&page=1&name=7.4-cli-stretch
Exists: https://hub.docker.com/_/php?tab=tags&page=1&name=7.4-cli-bu

2020-04-22 15:10 UTC, mohanelamurugan commented on images/php/7.4-cli/Dockerfile
> +FROM php:7.4-cli-stretch
Sure, Thanks. Let me use buster image and test it in my local

2020-04-23 11:19 UTC, mohanelamurugan commented on images/php/7.4-cli/Dockerfile
> +FROM php:7.4-cli-stretch
I just did that and tested it in my local

2020-04-23 11:20 UTC, mohanelamurugan commented
@shiftedreality I have made changes to comply with 7.4 images. Please do review it

2020-04-24 19:28 UTC, shiftedreality approved these changes

2020-04-28 19:45 UTC, arhiopterecs approved these changes

2020-04-29 19:01 UTC, mveeramneni commented
QA Approved

2020-04-29 19:10 UTC, merged