Added Blackfire support
magento/magento-cloud-docker pull request #202
Opened 2020-04-22 13:46 UTC by drpayyne

### Description

Added Blackfire support for magento cloud docker development

### Fixed Issue

-  magento/magento-cloud-docker#131: Add Blackfire.io to Cloud Docker

### Manual testing scenarios
1. Add Blackfire configuration to `.magento.app.yaml` under `runtime.extensions` as described below.  
    ```
    runtime:
      extensions:
        - random-extension-here
        -
          name: blackfire
          configuration:
            server_id: SERVER_ID
            server_token: SERVER_TOKEN
            client_id: CLIENT_ID
            client_token: CLIENT_TOKEN
    ```
2. Generate customized (Blackfire supported) PHP images and Docker configuration as described in [docker configuration generator](https://devdocs.magento.com/cloud/reference/ece-tools-reference.html#docker-configuration-generator) and [docker development](https://devdocs.magento.com/cloud/docker/docker-development.html).
3. Follow the rest of the guide linked [above](https://devdocs.magento.com/cloud/docker/docker-development.html) by bringing up the containers and deploying Magento.
4. Ensure necessary containers are up and running.
5. Install a profiling client as described in [Blackfire documentation](https://blackfire.io/docs/up-and-running/installation#install-a-profiling-client).
6. Profile the Magento website.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-22 14:52 UTC, shiftedreality commented
Hello @drpayyne,

Please fix static tests so we can begin reviewing this PR

2020-04-23 08:25 UTC, drpayyne commented
Hey @shiftedreality, the integration tests failed since it's testing the Blackfire extension being enabled as a top level node under `runtime.extensions` (without configuration) whereas this PR uses _only_ the structure described in the description to enable Blackfire and use its configuration. Just wanted to explain why I'm modifying the integration test. Thanks.

2020-05-01 14:22 UTC, NadiyaS submitted a review, later dismissed

2020-05-01 16:09 UTC, BaDos submitted a review, later dismissed

2020-05-01 19:47 UTC, sikharam-adb submitted a review, later dismissed

2020-05-05 02:55 UTC, andriyShevtsov commented
@drpayyne May you please help me to resolve this error. I got it after  ```docker-compose run build cloud-build```:

```Starting magento-cloud_db_1            ... done
[ ok ] Starting enhanced syslogd: rsyslogd.
error: 'blackfire' does not exist
usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
Possible values for module-name:
bcmath.so bz2.so calendar.so exif.so gd.so geoip.so gettext.so gmp.so igbinary.so imagick.so imap.so intl.so ioncube.so ldap.so mailparse.so msgpack.so mysqli.so oauth.so opcache.so pcntl.so pcov.so pdo_mysql.so propro.so pspell.so raphf.so recode.so redis.so shmop.so soap.so sockets.so sodium.so sysvmsg.so sysvsem.so sysvshm.so tidy.so xdebug.so xmlrpc.so xsl.so yaml.so zip.so
Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.```

I have blackfire in magento.app.yaml and docker-compose.yaml

And one more question. May you please explain why we need this settings? 
``` configuration:
        server_id: SERVER_ID
        server_token: SERVER_TOKEN
        client_id: CLIENT_ID
        client_token: CLIENT_TOKEN```
Can't it work the same as in cloud? Previously we just  provided extension name.

2020-05-05 03:03 UTC, drpayyne commented
Hi @andriyShevtsov, I think you may have missing creating a customized PHP image with the Blackfire probe in it. You can follow this guide (https://blackfire.io/docs/integrations/docker/index) to create that. That should resolve the missing extension (Blackfire probe) error.

About the configuration settings, we'll need to provide the Blackfire settings (obtained from Blackfire account) to the Docker containers, hence we're providing those values. I'm not sure how it works in Magento Cloud independently (I'm guessing the Cloud instance has it in env variables which are auto picked up), but for Docker, we have to provide these config values in some way.

2020-05-05 03:08 UTC, drpayyne commented
I added a new step 3 in the description. Missed that out somehow, sorry. Thanks, @andriyShevtsov.

2020-05-05 19:06 UTC, shiftedreality commented
@drpayyne it looks like you need to regenerate PHP  images and include them in PR

2020-05-06 01:30 UTC, drpayyne commented
Hi @shiftedreality, I've pushed the Blackfire injected PHP Dockerfiles now. I misunderstood that the user has to generate the PHP images when required, my bad.

2020-05-06 20:08 UTC, andriyShevtsov commented
@drpayyne I can't build  image for php-fpm 7.2 locally:
```Step 18/38 : RUN curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s \   && https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;")   && mkdir -p /tmp/blackfire   && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire   && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so   && ( echo extension=blackfire.so   && echo blackfire.agent_socket=tcp://blackfire:8707 ) > $(php -i | grep "additional .ini" | awk '{print $9}')/blackfire.ini   && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
 ---> Running in c461d25c6dc0
The command '/bin/sh -c curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s \   && https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;")   && mkdir -p /tmp/blackfire   && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire   && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so   && ( echo extension=blackfire.so   && echo blackfire.agent_socket=tcp://blackfire:8707 ) > $(php -i | grep "additional .ini" | awk '{print $9}')/blackfire.ini   && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz' returned a non-zero code: 3
```

2020-05-07 23:03 UTC, drpayyne commented on images/php/7.2-cli/Dockerfile
> +RUN curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
Hi @shiftedreality, I just figured out that the error @andriyShevtsov faced is due to the linebreak I introduced here after the static tests failed in my initial commits. I have now reverted the linebreak as you can see above in line 125. But my static tests should be failing for exceeding line length. Is there another way to add a line break in this PHP class but not appear in the bash script or should we ignore line length warning for this file or method since we have bash scripts involved?

Thanks.

2020-05-11 17:11 UTC, shiftedreality commented on images/php/7.2-cli/Dockerfile
> +RUN curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
Hello @drpayyne 

It seems to fail on `ExtensionResolver.php`, adding `phpcs:disable` and `pchs:enable` should be fine in this case:

```
                    // phpcs:disable
                    self::EXTENSION_INSTALLATION_SCRIPT => <<< BASH
curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;")
mkdir -p /tmp/blackfire
tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire
mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so
( echo extension=blackfire.so
echo blackfire.agent_socket=tcp://blackfire:8707 ) > $(php -i | grep "additional .ini" | awk '{print $9}')/blackfire.ini
rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
BASH
                ]
                // phpcs:enable
```

2020-05-11 17:17 UTC, drpayyne commented on images/php/7.2-cli/Dockerfile
> +RUN curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
Done, @shiftedreality. Thank you!

2020-05-12 17:01 UTC, shiftedreality approved these changes

2020-05-12 17:14 UTC, sikharam-adb approved these changes

2020-05-12 17:30 UTC, NadiyaS approved these changes

2020-05-13 21:04 UTC, shiftedreality requested changes

2020-05-13 21:04 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_BLACKFIRE)) {
@drpayyne this is not needed actually.
You just have to include updated images into git, which is included already. Please revert this change

2020-05-13 21:34 UTC, andriyShevtsov commented
QA approved

2020-05-14 11:35 UTC, drpayyne commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_BLACKFIRE)) {
Hi @shiftedreality, sure, but if Blackfire is enabled, we would _have_ to use the custom images using the `context` key, right? So what's the reason to not include the custom image context for the `build` and `fpm` services? :thinking:

2020-05-14 13:04 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_BLACKFIRE)) {
`context` is needed only when you want to build from sources. Once I merge this PR, the images will be updated on Docker Hub. So the change should be done for `Dockerfile`, what you've already did

2020-05-14 13:28 UTC, drpayyne commented on src/Compose/ProductionBuilder.php
> +        if ($config->hasServiceEnabled(ServiceInterface::SERVICE_BLACKFIRE)) {
Oh, gotcha. I wasn't aware of the Docker Hub part. I'll update my PR, thanks!

2020-05-14 13:48 UTC, shiftedreality commented
No additional QA needed, as changes do not affect functionality

2020-05-14 15:33 UTC, merged