Upgrade PHPUnit to version 8
magento/magento-cloud-docker pull request #207
Opened 2020-04-30 10:12 UTC by G-Arvind

### Description

Since PHPUnit 7 is already deprecated and PHPUnit 8 is stable, The PHPUnit should be upgraded to version 8

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#193: Upgrade PHPUnit to version 8

### Manual testing scenarios

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-04-30 10:51 UTC, G-Arvind commented
Hi,
The static-unit for PHP 7.1 is failing as the PHPUnit 8 doesn't support PHP 7.1
![Screenshot from 2020-04-30 16-20-46](https://user-images.githubusercontent.com/30662691/80702379-97b88500-8afe-11ea-96de-fb68412c4230.png)

2020-04-30 18:43 UTC, shiftedreality commented
@G-Arvind please exclude 7.1 checks

2020-05-01 04:45 UTC, G-Arvind commented
> @G-Arvind please exclude 7.1 checks
HI @shiftedreality 
Excluded PHP 7.1 from Travis. (Build Succeeded)
Thanks

2020-05-01 16:07 UTC, shiftedreality commented
Thanks @G-Arvind 

The changes overall look good, but since it affects FT, we'll need to discuss this internally if we're ok to drop PHP 7.1 support in the next minor release.

Putting on hold for now.

2020-05-04 21:21 UTC, YPyltiai commented
Discussed on call today - good to drop PHP 7.1 for Docker 1.1.0.

2020-05-11 19:50 UTC, shiftedreality requested changes

2020-05-11 19:50 UTC, shiftedreality commented on composer.json
> +        "phpunit/phpunit": "^8.5",
Please bump PHP version to `^7.2` in `require` section

2020-05-11 19:52 UTC, shiftedreality commented on .travis.yml
> -      php: '7.1'
Please also remove `PHP 7.1` images and `7.1` version from `\Magento\CloudDocker\Command\Image\GeneratePhp`

2020-05-12 16:38 UTC, G-Arvind commented on composer.json
> +        "phpunit/phpunit": "^8.5",
@shiftedreality Changed the PHP version to `^7.2`. Thanks.

2020-05-12 16:39 UTC, G-Arvind commented on .travis.yml
> -      php: '7.1'
@shiftedreality Removed the `PHP 7.1` images and `7.1` version from `magento-cloud-docker/src/Command/Image/GeneratePhp.php`.

Thanks.

2020-05-12 19:54 UTC, shiftedreality approved these changes

2020-05-12 19:57 UTC, michaelcasey316 approved these changes

2020-05-13 14:14 UTC, shiftedreality commented
No functionality changed. QA is not needed.

2020-05-13 14:14 UTC, merged