include ssh client to make use of ssh-agent forwarding for composer
magento/magento-cloud-docker pull request #215
Opened 2020-05-15 20:59 UTC by keithbentrup

### Description

This PR build off of https://github.com/magento/magento-cloud-docker/pull/209.
Many composer.json files include private git repos that need an ssh client included for various composer commands. This PR includes the ssh client and enables the local ssh-agent so composer commands work as expected.

### Manual testing scenarios

1. push the new images with the ssh client to the docker hub
2. verify access:
`./magento-docker php 7.3 ssh -T git@github.com`
You should see:
`Hi <GITHUBUSERNAME>! You've successfully authenticated, but GitHub does not provide shell access.`
3. run `composer install` with a private repo that the container would not normally have access to but the credentials are available in your ssh-agent.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-05-18 17:43 UTC, billygilbert submitted a review, later dismissed

2020-05-18 22:36 UTC, arhiopterecs commented on images/php/7.4-cli/Dockerfile
> +ENV COMPOSER_MEMORY_LIMIT -1
Why did you add this?
Did you have a memory problem with composer?
Was this problem observed only for version 7.4?

2020-05-18 22:36 UTC, arhiopterecs commented on dist/bin/magento-docker
> +            "magento/magento-cloud-docker-php:${version}-cli-1.1" "$@"
Why did you add “1.1” at the end?

2020-05-19 15:00 UTC, keithbentrup commented on images/php/7.4-cli/Dockerfile
> +ENV COMPOSER_MEMORY_LIMIT -1
I didn't add it. These Dockerfiles are generated from a template. Review the template to see why it's there, and when it was introduced to understand why it wasn't on the previous 7.4-cli/Dockerfile.

2020-05-19 15:05 UTC, keithbentrup commented on dist/bin/magento-docker
> +            "magento/magento-cloud-docker-php:${version}-cli-1.1" "$@"
Well, 1.0 won't have the ssh-client and 1.1 isn't "released" yet as far as I understand. Presumably, it would be the first with the ssh-client, but you can adapt for whichever target tag you need.

2020-05-19 17:48 UTC, arhiopterecs submitted a review, later dismissed

2020-05-20 15:54 UTC, shiftedreality requested changes

2020-05-20 15:54 UTC, shiftedreality commented on dist/bin/magento-docker
> +            "magento/magento-cloud-docker-php:${version}-cli-1.1" "$@"
Since we don't need any functionality from Cloud Docker image, I would recommend using official PHP images here instead to not think about the versioning

2020-05-21 17:40 UTC, keithbentrup commented on dist/bin/magento-docker
> +            "magento/magento-cloud-docker-php:${version}-cli-1.1" "$@"
@shiftedreality But you need the ssh client that was added to the Cloud Docker image (see changes) so that composer can clone from private repos (via ssh - typical method) which is the point of the PR.

2020-05-21 17:44 UTC, shiftedreality commented on dist/bin/magento-docker
> +            "magento/magento-cloud-docker-php:${version}-cli-1.1" "$@"
I see. Good then

2020-05-21 17:44 UTC, shiftedreality submitted a review, later dismissed

2020-06-02 04:59 UTC, andriyShevtsov commented
@keithbentrup May you please provide test steps for locally builded images?

2020-06-02 13:29 UTC, keithbentrup commented
@andriyShevtsov I explained how to test already. What have you tried? What was the result?

2020-06-02 17:13 UTC, andriyShevtsov commented
@keithbentrup @shiftedreality  I have next error:
```
./bin/magento-docker php 7.3 ssh -T git@github.com                                                                                                         ✔  10374  10:12:56
[....] Starting enhanced syslogd: rsyslogdrsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [v8.1901.0 try https://www.rsyslog.com/e/2145 ]
. ok
git@github.com: Permission denied (publickey).
```

According to code  key should be taken from host machine but looks like it wasn't. I suppose it works differently on Mac because next folder absent:
```
if [[ $(uname) = Darwin ]]; then
            # https://docs.docker.com/docker-for-mac/osxfs/#ssh-agent-forwarding (D4M > 2.2)
            SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
```

2020-06-02 17:57 UTC, keithbentrup commented
@andriyShevtsov The comment in the code links to the docker docs explaining this setup. It's the docker team's way of doing this on Docker for Mac > 2.2. The path doesn't actually exist on the host machine. 
However, I do see an error that explains your result. There should be an `export` before `SSH_AUTH_SOCK`. I had probably already exported it. Then when running my example code in (without export), it worked because the var already existed in the environment.

2020-06-02 19:26 UTC, billygilbert approved these changes

2020-06-02 19:27 UTC, arhiopterecs approved these changes

2020-06-02 19:45 UTC, andriyShevtsov commented
QA approved

2020-06-02 20:06 UTC, shiftedreality commented
@keithbentrup please provide minimal documentation for this feature

2020-06-02 22:54 UTC, keithbentrup commented
I'm not sure there needs to be any separate documentation aside from the main documentation for  `magento-docker php`. That sub-command exists so users can run `composer install` independent of their local php version as may be required by the composer.json that they want to install.

While documenting that feature, I would simply add as a parenthetical remark _"also supports private repos cloned over ssh using your ssh-agent."_

If they have their ssh-agent running (and what dev doesn't?), there's nothing special for them to do.

2020-06-03 13:20 UTC, merged