MCLOUD-6660: Add possibility to disable MailHog
magento/magento-cloud-docker pull request #274
Opened 2020-08-12 20:21 UTC by oshmyheliuk

### Description

Added possibility to disable MailHog.
Removed unused code.
https://jira.corp.magento.com/browse/MCLOUD-6660

### Manual testing scenarios

1. ...
2. ...

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

2020-08-13 15:42 UTC, shiftedreality requested changes

2020-08-13 15:42 UTC, shiftedreality commented on src/Config/Source/CliSource.php
> +                $service . '.enabled' => !$this->input->getOption($option)
It should be the same as old code

2020-08-13 15:42 UTC, shiftedreality commented on src/Config/Source/CliSource.php
> +                $service . '.enabled' => !$this->input->getOption($option)
Move the default enabled value to `CloudSource`

2020-08-13 20:51 UTC, oshmyheliuk commented on src/Config/Source/CliSource.php
> +                $service . '.enabled' => !$this->input->getOption($option)
Moved

2020-08-13 21:22 UTC, shiftedreality approved these changes

2020-08-14 14:22 UTC, arhiopterecs approved these changes

2020-08-14 14:32 UTC, BaDos approved these changes

2020-08-14 21:03 UTC, mveeramneni commented
QA Approved

2020-08-15 15:10 UTC, merged