MCLOUD-6430: Xdebug not working on Magento Cloud Docker 1.1
magento/magento-cloud-docker pull request #282
Opened 2020-08-27 23:47 UTC by oshmyheliuk

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

2020-08-28 14:54 UTC, NadiyaS commented on src/Compose/ProductionBuilder.php
> +            $envVariables = ['PHP_EXTENSIONS' => implode(' ', array_unique(array_merge($phpExtensions, ['xdebug'])))];
why do you merge with xdebug here?

2020-08-28 14:57 UTC, oshmyheliuk commented on src/Compose/ProductionBuilder.php
> +            $envVariables = ['PHP_EXTENSIONS' => implode(' ', array_unique(array_merge($phpExtensions, ['xdebug'])))];
Because this configuration only for `fpm_xdebug` container and it needs to have enabled `xdebug` extension.
`$phpExtensions` may not have `xdebug` if it not set-up in `.magento.app.yaml`

2020-08-31 16:30 UTC, NadiyaS approved these changes

2020-08-31 16:42 UTC, shiftedreality requested changes

2020-08-31 16:42 UTC, shiftedreality commented on images/php/7.2-fpm/docker-entrypoint.sh
> +if [[ "$SET_DOCKER_HOST" = "true" ]]; then
Can we have it enabled by default?

2020-08-31 17:26 UTC, oshmyheliuk commented on images/php/7.2-fpm/docker-entrypoint.sh
> +if [[ "$SET_DOCKER_HOST" = "true" ]]; then
Why do we need it by default? This option has a sense only for Linux system.
Also I tested it on macOS with generated `host.docker.inernal` and xdebug didn't work.

2020-08-31 17:51 UTC, shiftedreality commented on images/php/7.2-fpm/docker-entrypoint.sh
> +if [[ "$SET_DOCKER_HOST" = "true" ]]; then
Ic, thanks

2020-08-31 17:51 UTC, shiftedreality approved these changes

2020-09-01 20:21 UTC, mveeramneni commented
Tested in MacOS and it's working fine. @BaDos is testing in his virual box

2020-09-02 05:12 UTC, arhiopterecs approved these changes

2020-09-02 16:50 UTC, BaDos commented
Tested on my linux machine, it works.
QA approved.

2020-09-02 16:51 UTC, merged