MCLOUD-6898: Add option to customize port for MailHog
magento/magento-cloud-docker pull request #290
Opened 2020-09-09 22:50 UTC by BaDos

### Description

Added options to configure HTTP and SMTP ports for MailHog

### Fixed Issues (if relevant)

https://jira.corp.magento.com/browse/MCLOUD-6898

### Manual testing scenarios

Covered with Integration and Functional tests

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

2020-09-14 21:10 UTC, shiftedreality commented on src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
>      restart: always
Please remove `restart: always` since it causes issues

2020-09-14 21:32 UTC, BaDos commented on src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
>      restart: always
Done.

2020-09-14 21:37 UTC, shiftedreality requested changes

2020-09-14 21:37 UTC, shiftedreality commented on src/Compose/ProductionBuilder.php
> +                            ($config->getMailHogSmtpPort() ?: '1025').':1025',
Move defaults port to source where http ports located

2020-09-15 07:29 UTC, arhiopterecs approved these changes, later dismissed

2020-09-15 14:40 UTC, BaDos commented on src/Compose/ProductionBuilder.php
> +                            ($config->getMailHogSmtpPort() ?: '1025').':1025',
Done

2020-09-15 16:21 UTC, shiftedreality approved these changes

2020-09-15 16:25 UTC, arhiopterecs approved these changes

2020-09-16 03:46 UTC, andriyShevtsov commented
QA approved

2020-09-16 15:24 UTC, merged