Make <host.docker.internal> platform independent
magento/magento-cloud-docker pull request #298
Opened 2020-12-12 16:41 UTC by IgorVitol

### Description
It is not possible to generate unified **docker-compose** script for different operation systems because of requirement to set additional ENV variable for Ubuntu - "**SET_DOCKER_HOST**" (if you want to use XDEBUG). If it is set - docker container will install additional package "**iproute2**" and override **/etc/hosts** file (will add - "**host.docker.internal**" line). 

On **Windows/Mac** it is available by in-built DNS server, so this variable should be used only on **Linux**. Currently my goal to setup single behavior for all our devs and the only thing which I need to solve by workaround is this variable.

**This PR includes:**
1. "iproute2" package added to FPM image during image build (removed it's installing from startup entry-point script).
2. Added check for "host.docker.internal" availability - if not available - add it.
This will be done once at first container startup - on the next startup for the same container - "host.docker.internal" will be available already.
3. Removed additional option - "**--set-docker-host**" and it's ENV variable "**SET_DOCKER_HOST**", since this is not needed anymore.
4. Tested on Ubuntu/Windows/Mac

### Manual testing scenarios
1. Configure Xdebug on Windows / Ubuntu - it should work using same behavior. You don't need to use custom XDEBUG_HOST value or "**--set-docker-host**" option.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

2020-12-16 18:29 UTC, shiftedreality commented
@mattskr could you help with this review?

2020-12-16 18:31 UTC, shiftedreality requested changes

2020-12-16 18:31 UTC, shiftedreality commented on src/Command/BuildCompose.php
> -            )->addOption(
Let's make it deprecated, to not break BC. And remove functionality, associated with option

2020-12-16 18:35 UTC, shiftedreality commented
@IgorVitol thank you for your submisssion! Overall looks good, please merge the latest changes and solve conflicts

2020-12-16 23:17 UTC, IgorVitol commented
@shiftedreality Done, pls check again

2020-12-16 23:53 UTC, IgorVitol commented
@NadiyaS Just in case letting you know, that this PR is updated as well

2020-12-17 01:53 UTC, NadiyaS commented
@magento import pr to magento-commerce/magento-cloud-docker

2020-12-17 01:53 UTC, NadiyaS commented
Thank you @IgorVitol 
This PR will be added after 1.2.1 release as we need more time to process it.

2020-12-17 01:54 UTC, magento-engcom-team commented
@NadiyaS the pull request successfully imported.

2020-12-22 18:38 UTC, shiftedreality approved these changes

2021-01-06 17:17 UTC, oshmyheliuk approved these changes

2021-01-28 23:36 UTC, oshmyheliuk commented
@IgorVitol Thank you for your contribution, your pr has been merged from our internal repository.
This one wasn't automatically marked as merged as it has an additional merge commit which was added after this PR was imported in our internal repo.

2021-01-28 23:36 UTC, closed without merging