Magecloud 2790
magento/magento-cloud-docker pull request #31
Opened 2019-07-22 15:28 UTC by shiftedreality

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2019-07-22 15:28 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento-cloud-docker?pullRequest=31) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-cloud-docker?pullRequest=31) before we can accept your contribution.<br/>

2019-08-21 21:16 UTC, arhiopterecs requested changes

2019-08-21 21:16 UTC, arhiopterecs commented on dist/mutagen.sh
> +       --ignore=/generated \
In case if some user will be used `xdebug` and in call list will be present some generated class it can confuse a user 
Maybe, make sense add an option to indicate which necessary directories will be synchronized
```
$mutagen.sh --sync=generated
```

2019-08-21 21:16 UTC, arhiopterecs commented on images/php/7.0-cli/Dockerfile
> +RUN mkdir ${MAGENTO_ROOT} && chown www:www ${MAGENTO_ROOT}
You can use an alternative path
It has less code
```
RUN mkdir -p  ${MAGENTO_ROOT}/{vendor,generated,var,setup,app/etc,pub/static,pub/media} \
chown -R ${MAGENTO_ROOT}
```

2019-08-22 14:33 UTC, shiftedreality commented on dist/mutagen.sh
> +       --ignore=/generated \
Makes sense, will remove this for now

2019-08-22 14:33 UTC, shiftedreality commented on images/php/7.0-cli/Dockerfile
> +RUN mkdir ${MAGENTO_ROOT} && chown www:www ${MAGENTO_ROOT}
It's being generated programmatically, so should be fine

2019-08-23 21:20 UTC, michaelcasey316 approved these changes

2019-08-26 17:39 UTC, arhiopterecs approved these changes

2019-09-05 04:20 UTC, andriyShevtsov commented
QA approved

2019-09-05 19:48 UTC, andriyShevtsov commented
QA approved

2019-09-09 15:49 UTC, merged