Updated README.md
magento/magento-cloud-docker pull request #39
Opened 2019-08-15 15:25 UTC by YPyltiai

Updated README.md

2019-08-15 15:25 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento-cloud-docker?pullRequest=39) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-cloud-docker?pullRequest=39) before we can accept your contribution.<br/>

2019-08-15 16:08 UTC, hguthrie reviewed
I added a few suggestions to tie in the "suite of tools" narrative and boost clarity.

2019-08-15 16:08 UTC, hguthrie commented on README.md
> +- [Magento Cloud Docker](https://github.com/magento/magento-cloud-docker) - functionality and images to deploy Cloud environments locally
```suggestion
- [Magento Cloud Docker](https://github.com/magento/magento-cloud-docker) - package with images and functionality to deploy Cloud environments locally
```

2019-08-15 16:18 UTC, hguthrie commented on README.md
> +- [Magento Cloud Components](https://github.com/magento/magento-cloud-components) - package with extended core functionality for Cloud
Also, you called this a `module` in the cloud-components repo. Is it a package or a module?

2019-08-15 16:39 UTC, YPyltiai commented on README.md
> +- [Magento Cloud Components](https://github.com/magento/magento-cloud-components) - package with extended core functionality for Cloud
@hguthrie both. When referring to github it is package (code), while on the high level it is module. So this should be fine to leave, I think

2019-08-16 14:56 UTC, shiftedreality approved these changes

2019-08-16 18:43 UTC, meker12 requested changes

2019-08-16 18:43 UTC, meker12 commented on README.md
> +Magento Cloud Docker is a package—part of the [Magento Cloud Suite](#magento-cloud-suite)—designed to develop, test, and deploy your Magento Commerce store. The Magento Cloud Docker implementation de
```suggestion
Magento Cloud Docker is a package—part of the [Magento Cloud Suite](#magento-cloud-suite)—designed to develop, test, and deploy your Magento Commerce store. The Magento Cloud Docker implementation deploys Cloud projects to a local workstation so that you can develop and test your code in a simulated Cloud environment.
```

2019-08-19 18:07 UTC, merged

2019-08-19 19:33 UTC, meker12 reviewed
LGTM +1 OK to merge.