MAGECLOUD-4053: Windows compatibility is broken
magento/magento-cloud-docker pull request #64
Opened 2019-09-24 20:35 UTC by shiftedreality

### Description

### Fixed Issues (if relevant)

1. https://magento2.atlassian.net/browse/MAGECLOUD-4053
2. https://github.com/magento/magento-cloud-docker/issues/69

### Manual testing scenarios

For Windows:

> Add `.env file` with
`WINDOWS_PWD=PATH_TO_PROJECT_FOLDER`

1. https://jira.corp.magento.com/browse/MAGECLOUD-66
2. https://jira.corp.magento.com/browse/MAGECLOUD-116
3. On Windows: https://jira.corp.magento.com/browse/MAGECLOUD-66
4. Using option `--no cron 1` https://jira.corp.magento.com/browse/MAGECLOUD-66

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2019-09-26 19:52 UTC, bbatsche requested changes

2019-09-26 19:52 UTC, bbatsche commented on config/services.xml
> +        </service>
Why the change from using the map constant to passing in through configuration? I think either way is fine, I'm just curious about the benefit?

2019-09-26 19:52 UTC, bbatsche commented on src/Compose/FunctionalBuilder.php
> +            $converter, $phpExtension,
Need a new line here

2019-09-26 19:52 UTC, bbatsche commented on src/Compose/FunctionalBuilder.php
> +    public function __construct(
I'm not sure why you're overriding the `__construct()` method here, it looks like it takes all the same arguments as its parent?

2019-09-26 19:52 UTC, bbatsche commented on src/Service/ServiceFactory.php
> +                'extends' => 'generic'
Should these all be `'extends' => static::SERVICE_GENERIC`?

2019-09-26 19:55 UTC, shiftedreality commented on config/services.xml
> +        </service>
Technically Functional builder must be within ECE-Tools repo. Adding Symfony DI later will give as a possibility to inject a line with dependency

2019-09-27 15:13 UTC, shiftedreality commented on src/Compose/FunctionalBuilder.php
> +            $converter, $phpExtension,
Fixed

2019-09-27 15:13 UTC, shiftedreality commented on src/Compose/FunctionalBuilder.php
> +    public function __construct(
I need one depnendency `$fileList`

2019-09-27 15:13 UTC, shiftedreality commented on src/Service/ServiceFactory.php
> +                'extends' => 'generic'
Fixed

2019-09-27 15:53 UTC, bbatsche requested changes

2019-09-27 15:53 UTC, bbatsche commented on src/Compose/FunctionalBuilder.php
> +    public function __construct(
Ok, but `FileList` is already a dependency of `ProductionBuilder`, you just changed it from `protected` to `private` in this very same PR. Leave it `protected` and there's no need to override `__construct()` here.

2019-09-27 15:56 UTC, shiftedreality commented
We should avoid protected modifier, it's used only in few methods as it's too tricky to do this without inheritance

2019-09-30 16:00 UTC, shiftedreality commented on src/Compose/FunctionalBuilder.php
> +    public function __construct(
We should avoid protected modifier, it's used only in few methods as it's too tricky to do this without inheritance

2019-10-07 18:45 UTC, bbatsche approved these changes

2019-10-07 18:54 UTC, oshmyheliuk approved these changes

2019-10-07 18:56 UTC, BaDos approved these changes

2019-10-14 16:00 UTC, oshmyheliuk commented
QA on the Windows environment is approved.
For me next format `WINDOWS_PWD=/C/path/to/magento/cloud/` works fine.

2019-10-14 17:51 UTC, andriyShevtsov commented
QA approved

2019-10-14 17:55 UTC, merged