MAGECLOUD-4163: Using official images for Varnish and TLS.
magento/magento-cloud-docker pull request #83
Opened 2019-10-23 15:57 UTC by sikharam-adb

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2019-10-28 16:26 UTC, bbatsche approved these changes
Nothing looks wrong, but I just want some clarity on a couple of questions

2019-10-28 16:26 UTC, bbatsche commented on images/varnish/4.0/Dockerfile
> +FROM centos:centos7
Why CentOS? Most docker images I've seen are either Debian or Alpine based.

2019-10-28 16:26 UTC, bbatsche commented on src/Command/BuildCompose.php
> +            ->addOption(
Did you run this through a style check or something? Otherwise, just changing whitespace in this file seems unnecessary.

2019-10-29 15:10 UTC, shiftedreality requested changes

2019-10-29 15:10 UTC, shiftedreality commented on images/tls/Dockerfile
> +ENTRYPOINT ["/entrypoint.sh"]
Please add newline in each file

2019-10-29 15:10 UTC, shiftedreality commented on src/Command/BuildCompose.php
> +            ->addOption(
That's a recent update in PHPCS. Fixed in 1.0

2019-10-29 17:39 UTC, NadiyaS approved these changes

2019-10-29 17:49 UTC, sikharam-adb commented on images/varnish/4.0/Dockerfile
> +FROM centos:centos7
The current Varnish image is based off CentOS, and I have done the same.

2019-10-30 16:42 UTC, mveeramneni commented
QA Approved

2019-10-30 16:48 UTC, merged