Added Contribution guidelines
magento/magento-cloud-docker pull request #96
Opened 2019-11-06 21:04 UTC by meker12

### Description
Added contribution guidelines for the Magento Cloud Docker project

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2019-11-06 21:19 UTC, bbatsche requested changes

2019-11-06 21:19 UTC, bbatsche commented on .github/CONTRIBUTING.md
> +4. For larger features or changes, [open an issue](https://github.com/magento/adobe-stock-integration/issues) to discuss the proposed changes prior to development. Discussing the updates in advance c
Need to update the URL here

2019-11-06 21:19 UTC, bbatsche commented on .github/CONTRIBUTING.md
> +1. Search current [listed issues](https://github.com/magento/adobe-stock-integration/issues) (open or closed) for similar proposals of intended contribution before starting work on a new contribution
Also URL here

2019-11-06 21:19 UTC, bbatsche commented on .github/CONTRIBUTING.md
> +If you have any questions, join us in [#adobe-stock](https://magentocommeng.slack.com/messages/CH8BGFX9D) Slack chat. If you are not on our slack, [click here](http://tinyurl.com/engcom-slack) to joi
Should be #cloud-docker, and maybe check where the URL goes

2019-11-07 14:06 UTC, YPyltiai commented on .github/CONTRIBUTING.md
> +If you have any questions, join us in [#adobe-stock](https://magentocommeng.slack.com/messages/CH8BGFX9D) Slack chat. If you are not on our slack, [click here](http://tinyurl.com/engcom-slack) to joi
URL is wrong I think. We can just refer to absolute URL of the Slack space.

2019-11-07 14:14 UTC, YPyltiai requested changes

2019-11-07 14:14 UTC, YPyltiai commented on .github/CONTRIBUTING.md
> +Contributions can take the form of new components or features, changes to existing features, tests, bug fixes, or optimizations. You can also contribute new or updated documentation.
Remove `components`. It's referring to base Magento & not applicable here.

2019-11-07 14:14 UTC, YPyltiai commented on .github/CONTRIBUTING.md
> +The Magento Cloud development team and community maintainers review all issues and contributions submitted by the developer community in first in, first out order (FIFO). During the review process, r
`You have two weeks to respond to these requests. If we do not recieve a response, we close the pull request.` - not sure if we need this sentence. At this point there are not that many PRs, so we can wait.

2019-11-07 14:14 UTC, YPyltiai commented on .github/CONTRIBUTING.md
> +1. Contributions must adhere to the [Magento coding standards](https://devdocs.magento.com/guides/v2.3/coding-standards/bk-coding-standards.html).
@shiftedreality does it apply here?

2019-11-07 16:19 UTC, shiftedreality commented on .github/CONTRIBUTING.md
> +1. Contributions must adhere to the [Magento coding standards](https://devdocs.magento.com/guides/v2.3/coding-standards/bk-coding-standards.html).
Yes

2019-11-07 17:15 UTC, meker12 commented on .github/CONTRIBUTING.md
> +The Magento Cloud development team and community maintainers review all issues and contributions submitted by the developer community in first in, first out order (FIFO). During the review process, r
```suggestion
The Magento Cloud development team and community maintainers review all issues and contributions submitted by the developer community in first in, first out order (FIFO). During the review process, reviewers might notify a contributor to request clarification on the proposed changes.
```

2019-11-07 17:15 UTC, meker12 commented on .github/CONTRIBUTING.md
> +Contributions can take the form of new components or features, changes to existing features, tests, bug fixes, or optimizations. You can also contribute new or updated documentation.
```suggestion
Contributions can take the form of new features, changes to existing features, tests, bug fixes, or optimizations. You can also contribute new or updated documentation.
```

2019-11-07 17:17 UTC, meker12 commented on .github/CONTRIBUTING.md
> +If you have any questions, join us in [#adobe-stock](https://magentocommeng.slack.com/messages/CH8BGFX9D) Slack chat. If you are not on our slack, [click here](http://tinyurl.com/engcom-slack) to joi
I updated the URL to open the cloud-docker channel, and also changed #adobe-stock to #cloud-docker

2019-11-07 20:20 UTC, shiftedreality approved these changes

2019-11-07 21:29 UTC, shiftedreality submitted a review, later dismissed

2019-11-07 22:43 UTC, bbatsche requested changes

2019-11-07 22:43 UTC, bbatsche commented on .github/CONTRIBUTING.md
> +4. For PRs which include bug fixes include a step-by-step description of how to reproduce the bug in the pull request descroption.
"For PRs which include bug fixes, you must include a step-by-step description of how to reproduce the bug in the pull request description."

2019-11-07 22:43 UTC, bbatsche commented on .github/CONTRIBUTING.md
> +   * Proposed [documentation](https://devdocs.magento.com) updates: Submit developer documentation contributions from the [Magento DevDocs](https://github.com/magento/devdocs) repository. Submit upda
"Proposed [documentation](https://devdocs.magento.com) updates: Submit developer documentation contributions to the [Magento DevDocs](https://github.com/magento/devdocs) repository. Submit updates to Magento user documentation to the [Magento Merchant documentation](https://github.com/magento/merchdocs) repository."

2019-11-13 16:37 UTC, meker12 reviewed
Added recommended revisions using GitHub suggestion feature.

2019-11-13 16:37 UTC, meker12 commented on .github/CONTRIBUTING.md
> +4. For PRs which include bug fixes include a step-by-step description of how to reproduce the bug in the pull request descroption.
```suggestion
4. If your PR includes bug fixes, provide a step-by-step description of how to reproduce the bug in the pull request description.
```

2019-11-13 16:37 UTC, meker12 commented on .github/CONTRIBUTING.md
> +   * Proposed [documentation](https://devdocs.magento.com) updates: Submit developer documentation contributions from the [Magento DevDocs](https://github.com/magento/devdocs) repository. Submit upda
```suggestion
   * Proposed documentation updates: Submit developer documentation contributions to the Magento DevDocs repository. Submit updates to Magento user documentation to the Magento Merchant documentation repository.
```

2019-11-13 20:42 UTC, shiftedreality submitted a review, later dismissed

2019-11-13 22:16 UTC, meker12 commented on .github/CONTRIBUTING.md
> +   * Proposed documentation updates: Submit developer documentation contributions to the Magento DevDocs repository. Submit updates to Magento user documentation to the Magento Merchant documentation
```suggestion
   * Proposed documentation updates: Submit developer documentation contributions to the [Magento DevDocs repository](https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md). Submit updates to Magento user documentation to the [Magento Merchant documentation repository](https://github.com/magento/merchdocs/blob/master/.github/CONTRIBUTING.md).
```

2019-11-13 22:17 UTC, meker12 commented on .github/CONTRIBUTING.md
> +3. For PRs which include new logic or new features, you must also submit the following information along with the pull request
```suggestion
3. If your PR includes new logic or new features, you must also submit the following information along with the pull request
```

2019-11-14 18:13 UTC, shiftedreality approved these changes

2019-11-14 18:41 UTC, bbatsche approved these changes

2019-11-14 18:49 UTC, YPyltiai approved these changes

2019-11-14 18:53 UTC, merged