Magecloud 3598
magento/magento-cloud-docker pull request #97
Opened 2019-11-07 15:30 UTC by NadiyaS

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2019-11-13 15:19 UTC, shiftedreality requested changes

2019-11-13 15:19 UTC, shiftedreality commented on images/php/7.1-cli/bin/cloud-deploy
> +if [[ "$MAGENTO_RUN_MODE" == "production" ]]; then
Provided this implementation still does not track if Varnish is present. Should we consider it as a required service on Cloud Docker?

2019-11-13 15:19 UTC, shiftedreality commented on images/php/7.1-cli/bin/cloud-deploy
> +        output=$(magento-command config:set system/full_page_cache/caching_application 2)
Adding `--lock` would ensure the value won't get overwritten, and error code here is only expected if exception occured. Can be re-written in 

```
magento-command config:set system/full_page_cache/caching_application 2 --lock && magento-command setup:config:set --http-cache-hosts=varnish -n
```

2019-11-13 15:26 UTC, NadiyaS commented on images/php/7.1-cli/bin/cloud-deploy
> +        output=$(magento-command config:set system/full_page_cache/caching_application 2)
Actually, this value was added to DB for providing possibility to change this value from Admin UI.
And if this value exists in files we won't change it.

2019-11-13 15:30 UTC, NadiyaS commented on images/php/7.1-cli/bin/cloud-deploy
> +if [[ "$MAGENTO_RUN_MODE" == "production" ]]; then
We have this service by default, isn't it.

2019-11-13 19:19 UTC, michaelcasey316 commented on images/php/7.1-cli/bin/cloud-deploy
> +if [[ "$MAGENTO_RUN_MODE" == "production" ]]; then
Another possibility for testing for the presence of Varnish:

1. Change the Varnish config to emit headers that reveal when Varnish is in use (currently it hides everything).
2. Use cURL to read the headers from port 80/443 and check for the presence of the Varnish header.
3. Change the config depending on the results of the request.

2019-11-13 19:21 UTC, michaelcasey316 reviewed
I approve of the changes, though I'm not sure this satisfies the concern that someone might accidentally enable Varnish when it's not running in Docker. Will Magento set `full_page_cache/caching_application` to  `2` even when the Varnish server is not actually running?

2019-12-19 20:24 UTC, shiftedreality commented
Comment after latest public grooming:

We agreed to make varnish optional with `--no-varnish` option on both Developer and Production modes.
This will remove varnish as a service from resulting `docker-compose`.

The script should be able to detect the Varnish presence.

2020-01-06 21:10 UTC, shiftedreality approved these changes

2020-01-06 21:11 UTC, shiftedreality submitted a review, later dismissed
Overall looks good, you'll have to resolve conflicts after https://github.com/magento/magento-cloud-docker/pull/113

2020-01-07 15:39 UTC, shiftedreality submitted a review, later dismissed

2020-01-07 15:44 UTC, oshmyheliuk submitted a review, later dismissed

2020-01-07 17:49 UTC, shiftedreality submitted a review, later dismissed

2020-01-07 18:29 UTC, oshmyheliuk submitted a review, later dismissed

2020-01-07 22:08 UTC, YPyltiai commented
@aepod , @joeshelton-wagento , please take a look. This is the one we discussed during grooming.

2020-01-08 16:52 UTC, andriyShevtsov commented
QA approved

There no way to test flow with magento 2.1.x because of this issue https://magento2.atlassian.net/browse/MAGECLOUD-4979 so decided to skip it.

2020-01-09 19:31 UTC, shiftedreality approved these changes

2020-01-13 16:16 UTC, oshmyheliuk approved these changes

2020-01-14 16:56 UTC, merged